# https://www.youtube.com/playlist?list=PLNmsVeXQZj7rhjy2t320NvKKGwP6Rxnpg
title: "Assembler Lernen - Tutorial Deutsch"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665507903
sections:
  - id: section
    title: "Assembler Lernen - Tutorial Deutsch"
    description:
    lectures:
      - id: "UiqAq-iWHPI"
        title: "Assembler Tutorial #1 - Einleitung"
        description:
        type: youtube
        video_id: "UiqAq-iWHPI"
        duration: 531
      - id: "XFB_-UrrG3Y"
        title: "Assembler Tutorial #2 - GCC Assembler"
        description:
        type: youtube
        video_id: "XFB_-UrrG3Y"
        duration: 703
      - id: "P013kCzh4TA"
        title: "Assembler Tutorial #3 - Der Von Neumann Rechner"
        description:
        type: youtube
        video_id: "P013kCzh4TA"
        duration: 420
      - id: "9cOFFHvUwCs"
        title: "Assembler Tutorial #4 - abstrahierter Speicher"
        description:
        type: youtube
        video_id: "9cOFFHvUwCs"
        duration: 353
      - id: "-yNUND7FTHY"
        title: "Assembler Tutorial #5 - Movl, Movq etc"
        description:
        type: youtube
        video_id: "-yNUND7FTHY"
        duration: 118
      - id: "9i_1T-I8Guo"
        title: "Assembler Tutorial #6 - Der Stack"
        description:
        type: youtube
        video_id: "9i_1T-I8Guo"
        duration: 217
      - id: "xA81yEWRLQc"
        title: "Assembler Tutorial #7 - Prozeduren und Funktionen"
        description:
        type: youtube
        video_id: "xA81yEWRLQc"
        duration: 359
      - id: "jn53WnfxMPk"
        title: "Assembler Tutorial #8 - Einstiegspunkte und Ausgaben"
        description:
        type: youtube
        video_id: "jn53WnfxMPk"
        duration: 494
      - id: "dCSYVW6yfFI"
        title: "Assembler Tutorial #9 - Einen Integer ausgeben"
        description:
        type: youtube
        video_id: "dCSYVW6yfFI"
        duration: 165
      - id: "fEyGD-Qx7u8"
        title: "Assembler Tutorial #10 - Bedingte Ausgaben"
        description:
        type: youtube
        video_id: "fEyGD-Qx7u8"
        duration: 516
      - id: "M50Vv32yzzo"
        title: "Assembler Tutorial #11 - Sprungbefehle - Jump"
        description:
        type: youtube
        video_id: "M50Vv32yzzo"
        duration: 597
      - id: "IkVZc5MALi4"
        title: "Assembler Tutorial #12 - Einfache Arithmetische Befehle"
        description:
        type: youtube
        video_id: "IkVZc5MALi4"
        duration: 778
      - id: "zYeOSoIB8ag"
        title: "Assembler Tutorial #13 - Schleifen"
        description:
        type: youtube
        video_id: "zYeOSoIB8ag"
        duration: 376
      - id: "4f3t94Xwkvg"
        title: "Assembler Tutorial #14 - Logische Befehle"
        description:
        type: youtube
        video_id: "4f3t94Xwkvg"
        duration: 478
      - id: "lpKo0ZDJD2Q"
        title: "Assembler Tutorial #15 - Shift Befehle"
        description:
        type: youtube
        video_id: "lpKo0ZDJD2Q"
        duration: 452
      - id: "nvErXNcWTNg"
        title: "Assembler Tutorial #16 - Stack Frames"
        description:
        type: youtube
        video_id: "nvErXNcWTNg"
        duration: 273
      - id: "zcQAd3vIXAU"
        title: "Assembler Tutorial #17 - Der GCC Output"
        description:
        type: youtube
        video_id: "zcQAd3vIXAU"
        duration: 840
      - id: "BKmzY8Bu8GY"
        title: "Assembler Tutorial #18 - Inline Assembler - Assembler Code in C"
        description:
        type: youtube
        video_id: "BKmzY8Bu8GY"
        duration: 538
