# https://www.youtube.com/playlist?list=PLNmsVeXQZj7qff-bnM05OqSI0fx4GknZ6
title: "Binary Exploitation und Secure Coding für die Supporter"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665507832
sections:
  - id: section
    title: "Binary Exploitation und Secure Coding für die Supporter"
    description:
    lectures:
      - id: "3Tdx9HNfFco"
        title: "Binary Exploitation und Secure Coding in C 0x00"
        description:
        type: youtube
        video_id: "3Tdx9HNfFco"
        duration: 680
      - id: "w0OTPu0727Q"
        title: "Binary Exploitation 0x01   GDB"
        description:
        type: youtube
        video_id: "w0OTPu0727Q"
        duration: 1055
      - id: "5vaprZFAROE"
        title: "Binary Exploitation 0x02   Prozess Layout Stack und Heap"
        description:
        type: youtube
        video_id: "5vaprZFAROE"
        duration: 473
      - id: "lwG8NGgqcik"
        title: "Binary Exploitation 0x03   Buffer Overflows und Stack Smashing"
        description:
        type: youtube
        video_id: "lwG8NGgqcik"
        duration: 311
      - id: "5dguk0pTLec"
        title: "Binary Exploitation 0x04   Variablen ändern"
        description:
        type: youtube
        video_id: "5dguk0pTLec"
        duration: 739
      - id: "SYfoKZ-8eCw"
        title: "Binary Exploitation 0x05   Code Ausführung ändern"
        description:
        type: youtube
        video_id: "SYfoKZ-8eCw"
        duration: 924
      - id: "ATQiz5fEni4"
        title: "Binary Exploitation 0x06   Üben unter Windows Mac und Linux"
        description:
        type: youtube
        video_id: "ATQiz5fEni4"
        duration: 538
      - id: "E-S7cpv-9_A"
        title: "Binary Exploitation 0x07   Gezielt Variablen verändern"
        description:
        type: youtube
        video_id: "E-S7cpv-9_A"
        duration: 599
      - id: "WjWgBM74G-g"
        title: "Binary Exploitation 0x08   Nicht ASCII Werte nutzen"
        description:
        type: youtube
        video_id: "WjWgBM74G-g"
        duration: 524
      - id: "kQiBki9yddk"
        title: "Binary Exploitation 0x09   Ausführung verändern"
        description:
        type: youtube
        video_id: "kQiBki9yddk"
        duration: 489
      - id: "lPr5YOH5IO0"
        title: "Binary Exploitation 0x0a   Ausführung verändern II"
        description:
        type: youtube
        video_id: "lPr5YOH5IO0"
        duration: 637
      - id: "9k2MN_FBGVM"
        title: "Binary Exploitation 0x0b   Shellcode"
        description:
        type: youtube
        video_id: "9k2MN_FBGVM"
        duration: 1796
      - id: "eGyf_xcORcY"
        title: "Binary Exploitation 0x0c   Das NX Bit"
        description:
        type: youtube
        video_id: "eGyf_xcORcY"
        duration: 528
      - id: "vfS3UsKyGmg"
        title: "Binary Exploitation 0x0d   Return to LibC erklärt"
        description:
        type: youtube
        video_id: "vfS3UsKyGmg"
        duration: 340
      - id: "jPJK8u_D0Zw"
        title: "Binary Exploitation 0x0e   Stack Canaries"
        description:
        type: youtube
        video_id: "jPJK8u_D0Zw"
        duration: 277
      - id: "YL60WELLlZE"
        title: "Binary Exploitation 0x0f  ASLR und PIE"
        description:
        type: youtube
        video_id: "YL60WELLlZE"
        duration: 405
      - id: "_MCDmhUdivI"
        title: "Binary Exploitation 0x10  problematische Funktionen"
        description:
        type: youtube
        video_id: "_MCDmhUdivI"
        duration: 316
      - id: "dlz8x7WM1eI"
        title: "Binary Exploitation 0x11   Format String Leaks"
        description:
        type: youtube
        video_id: "dlz8x7WM1eI"
        duration: 607
      - id: "Pwco1NTsAVs"
        title: "Binary Exploitation 0x12   Format String Variablen ändern"
        description:
        type: youtube
        video_id: "Pwco1NTsAVs"
        duration: 520
      - id: "qaaY6KFIEaw"
        title: "Binary Exploitation 0x13   Format String An beliebige Orte schreiben"
        description:
        type: youtube
        video_id: "qaaY6KFIEaw"
        duration: 722
      - id: "HvzkKHbgcrI"
        title: "Binary Exploitation 0x13   Format String beliebige Werte schreiben"
        description:
        type: youtube
        video_id: "HvzkKHbgcrI"
        duration: 795
      - id: "j_dPzyYI--E"
        title: "Binary Exploitation 0x14   Integer Overflows"
        description:
        type: youtube
        video_id: "j_dPzyYI--E"
        duration: 342
      - id: "95VtC9s8RBY"
        title: "Binary Exploitation 0x15   Heap Overflows"
        description:
        type: youtube
        video_id: "95VtC9s8RBY"
        duration: 256
      - id: "hHWh9DfPlqw"
        title: "Binary Exploitation 0x16   Use after Free"
        description:
        type: youtube
        video_id: "hHWh9DfPlqw"
        duration: 582
      - id: "_jFt5HO0ZQc"
        title: "Binary Exploitation 0x17   No Free und Double Free"
        description:
        type: youtube
        video_id: "_jFt5HO0ZQc"
        duration: 447
      - id: "Z7ClHlFYRGQ"
        title: "Binary Exploitation 0x18   Abschließende Worte"
        description:
        type: youtube
        video_id: "Z7ClHlFYRGQ"
        duration: 298
