# https://www.youtube.com/playlist?list=PLNmsVeXQZj7oG-kkn36ZnDpRq6iahUXZS
title: "C++ Tutorial Deutsch"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665506460
sections:
  - id: section
    title: "C++ Tutorial Deutsch"
    description:
    lectures:
      - id: "Q7CnoMhUxWQ"
        title: "C Crashkurs Tutorial für Programmierer in ~45 Minuten"
        description:
        type: youtube
        video_id: "Q7CnoMhUxWQ"
        duration: 2640
      - id: "fypyXGaNFgg"
        title: "C++ Tutorial #1 - Installation und Setup"
        description:
        type: youtube
        video_id: "fypyXGaNFgg"
        duration: 593
      - id: "jZAaUJvqbPM"
        title: "C++ Tutorial #2 - Inputs und Outputs"
        description:
        type: youtube
        video_id: "jZAaUJvqbPM"
        duration: 278
      - id: "nIhTXXxl-Lc"
        title: "C++ Tutorial #3 - Strings"
        description:
        type: youtube
        video_id: "nIhTXXxl-Lc"
        duration: 781
      - id: "JytgNgE1CqQ"
        title: "C++ Tutorial #4 - Klassen"
        description:
        type: youtube
        video_id: "JytgNgE1CqQ"
        duration: 616
      - id: "z-2Od9wLzKM"
        title: "C++ Tutorial #5 - Konstruktoren"
        description:
        type: youtube
        video_id: "z-2Od9wLzKM"
        duration: 647
      - id: "Psdvmx-Hj-8"
        title: "C++ Tutorial #6 - Member Initialisierung und Pointer auf Objekte"
        description:
        type: youtube
        video_id: "Psdvmx-Hj-8"
        duration: 558
      - id: "uWiPVmOJdLo"
        title: "C++ Tutorial #7 - Kapselung mit private und public"
        description:
        type: youtube
        video_id: "uWiPVmOJdLo"
        duration: 541
      - id: "SML9OTNlAOg"
        title: "C++ Tutorial #8 - Operatoren überladen"
        description:
        type: youtube
        video_id: "SML9OTNlAOg"
        duration: 559
      - id: "vpaAQu7Lkfs"
        title: "C++ Tutorial #9 - this und Call by Reference"
        description:
        type: youtube
        video_id: "vpaAQu7Lkfs"
        duration: 394
      - id: "j1KKmMF1_Ys"
        title: "C++ Tutorial #10 - static - Klassenvariablen"
        description:
        type: youtube
        video_id: "j1KKmMF1_Ys"
        duration: 320
      - id: "eRg5EU2qq-k"
        title: "C++ Tutorial #11 - const"
        description:
        type: youtube
        video_id: "eRg5EU2qq-k"
        duration: 518
      - id: "Lh8tzIieBJU"
        title: "C++ Tutorial #12 - Header Files für Klassendefinitionen"
        description:
        type: youtube
        video_id: "Lh8tzIieBJU"
        duration: 496
      - id: "8prKOxAS_Co"
        title: "C++ Tutorial #13 - Friendship [Deutsch/German]"
        description:
        type: youtube
        video_id: "8prKOxAS_Co"
        duration: 267
      - id: "Ia1QE-RraGU"
        title: "C++ Tutorial #14 - Vererbung"
        description:
        type: youtube
        video_id: "Ia1QE-RraGU"
        duration: 468
      - id: "X8HqCZQr1PI"
        title: "C++ Tutorial #15 - Zugriffsmodifikatoren bei Vererbung"
        description:
        type: youtube
        video_id: "X8HqCZQr1PI"
        duration: 550
      - id: "esCBTBiMTNQ"
        title: "C++ Tutorial #16 - virtual und mehr zu Vererbung"
        description:
        type: youtube
        video_id: "esCBTBiMTNQ"
        duration: 610
      - id: "a3zvYc-txRo"
        title: "C++ Tutorial #17 - Mehrfachvererbung"
        description:
        type: youtube
        video_id: "a3zvYc-txRo"
        duration: 473
      - id: "qHQpz7UFvA0"
        title: "C++ Tutorial #18 - Abstraktheit und Interfaces"
        description:
        type: youtube
        video_id: "qHQpz7UFvA0"
        duration: 507
      - id: "wiW3hDyYvmc"
        title: "C++ Tutorial #19 - Multithreading"
        description:
        type: youtube
        video_id: "wiW3hDyYvmc"
        duration: 723
      - id: "bpRmoIWyZLE"
        title: "C++ Tutorial #20 - Multithreading #2"
        description:
        type: youtube
        video_id: "bpRmoIWyZLE"
        duration: 502
      - id: "1hO5O5t-9Ws"
        title: "Modern C++ - Die IDE CLion einrichten"
        description:
        type: youtube
        video_id: "1hO5O5t-9Ws"
        duration: 534
      - id: "VUuSzDQh8uo"
        title: "Modern C++ - Vector"
        description:
        type: youtube
        video_id: "VUuSzDQh8uo"
        duration: 805
      - id: "1grLmPPU9v0"
        title: "Modern C++ - Maps"
        description:
        type: youtube
        video_id: "1grLmPPU9v0"
        duration: 874
      - id: "rNnE37oObh4"
        title: "Modern C++ - Auto"
        description:
        type: youtube
        video_id: "rNnE37oObh4"
        duration: 675
      - id: "ljiP8T16ckU"
        title: "Modern C++ - nullptr"
        description:
        type: youtube
        video_id: "ljiP8T16ckU"
        duration: 607
      - id: "NIAJPOroh94"
        title: "Modern C++ - constexpr"
        description:
        type: youtube
        video_id: "NIAJPOroh94"
        duration: 809
      - id: "Dpm7gqLhPPk"
        title: "Modern C++ - Chrono"
        description:
        type: youtube
        video_id: "Dpm7gqLhPPk"
        duration: 356
      - id: "-Y4kigvvrAQ"
        title: "Modern C++ - If-Variablen-Scope"
        description:
        type: youtube
        video_id: "-Y4kigvvrAQ"
        duration: 525
      - id: "U-dZ4uaeMlo"
        title: "Modern C++ - initializer Lists"
        description:
        type: youtube
        video_id: "U-dZ4uaeMlo"
        duration: 483
      - id: "PjIR0QO2dGE"
        title: "Modern C++ - Mehrere Rückgabe-Werte"
        description:
        type: youtube
        video_id: "PjIR0QO2dGE"
        duration: 529
      - id: "F_Gn20Vr-1w"
        title: "Modern C++ - Raw Strings"
        description:
        type: youtube
        video_id: "F_Gn20Vr-1w"
        duration: 474
      - id: "b_rgiYG5xWs"
        title: "Modern C++ - Smart Pointer #1 - RAII [GERMAN/DEUTSCH]"
        description:
        type: youtube
        video_id: "b_rgiYG5xWs"
        duration: 751
      - id: "KNcqxpjO_vI"
        title: "Modern C++ - Smart Pointer #2 - Shared Pointer"
        description:
        type: youtube
        video_id: "KNcqxpjO_vI"
        duration: 648
      - id: "u2TME7SqLlo"
        title: "Modern C++ - Smart Pointer #3 - Unique Pointer"
        description:
        type: youtube
        video_id: "u2TME7SqLlo"
        duration: 569
      - id: "JYs5hroLTJE"
        title: "Modern C++ - Smart Pointer #4 - Weak Pointer"
        description:
        type: youtube
        video_id: "JYs5hroLTJE"
        duration: 547
      - id: "ryFOJlhb4nc"
        title: "Modern C++ - Filesystem: Ordner"
        description:
        type: youtube
        video_id: "ryFOJlhb4nc"
        duration: 559
      - id: "EowRm0EKWsg"
        title: "Modern C++ - Filesystem #2 - Dateien"
        description:
        type: youtube
        video_id: "EowRm0EKWsg"
        duration: 666
      - id: "cOXo09KHVtw"
        title: "Modern C++ - Lambdas und Functional C++"
        description:
        type: youtube
        video_id: "cOXo09KHVtw"
        duration: 649
      - id: "CF30r-A7uV8"
        title: "Modern C++ - Lambdas und Functional C++ #2 - Capture List"
        description:
        type: youtube
        video_id: "CF30r-A7uV8"
        duration: 604
      - id: "otInl-deYSk"
        title: "Modern C++ - Lambdas und Functional C++ #3 - Die Typen von Funktionen"
        description:
        type: youtube
        video_id: "otInl-deYSk"
        duration: 607
      - id: "Kzei0cT8bE8"
        title: "Modern C++ - OOP #1 - Delegate und Inheritance Constructors"
        description:
        type: youtube
        video_id: "Kzei0cT8bE8"
        duration: 472
      - id: "Dgh1I5x-g50"
        title: "Modern C++ - OOP #2 - override und final für virtual functions"
        description:
        type: youtube
        video_id: "Dgh1I5x-g50"
        duration: 435
      - id: "NCa-QKf5MZ8"
        title: "Modern C++ - noexcept"
        description:
        type: youtube
        video_id: "NCa-QKf5MZ8"
        duration: 301
      - id: "S1E0GD4UZMo"
        title: "Modern C++ - Parallelismus und Concurrency #1 - Threads erstellen"
        description:
        type: youtube
        video_id: "S1E0GD4UZMo"
        duration: 522
      - id: "2w4p0miwRzs"
        title: "Modern C++ - Parallelismus und Concurrency #2 - Mutex"
        description:
        type: youtube
        video_id: "2w4p0miwRzs"
        duration: 791
      - id: "8KO-q2SymjQ"
        title: "Modern C++ - Parallelismus und Concurrency #3 - Spinlocks"
        description:
        type: youtube
        video_id: "8KO-q2SymjQ"
        duration: 316
      - id: "9lz3j2BY9UY"
        title: "Modern C++ - Parallelismus und Concurrency #4 - Atomic Variablen"
        description:
        type: youtube
        video_id: "9lz3j2BY9UY"
        duration: 244
      - id: "E7E-KI9qX9M"
        title: "Modern C++ - Parallelismus und Concurrency #5 - Der Standard Daten Workflow"
        description:
        type: youtube
        video_id: "E7E-KI9qX9M"
        duration: 771
      - id: "DypE0Eg5qb4"
        title: "Modern C++ - Parallelismus und Concurrency #6 - Condition Variables"
        description:
        type: youtube
        video_id: "DypE0Eg5qb4"
        duration: 549
      - id: "wAqT0Jk4NYg"
        title: "Modern C++ - Parallelismus und Concurrency #7 - Asnyc und Futures"
        description:
        type: youtube
        video_id: "wAqT0Jk4NYg"
        duration: 615
      - id: "7IJdAKgJ_xE"
        title: "Modern C++ - Parallelismus und Concurrency #8 - Futures und Promises"
        description:
        type: youtube
        video_id: "7IJdAKgJ_xE"
        duration: 608
      - id: "9VlNjHhKHMc"
        title: "Modern C++ - Parallelismus und Concurrency #9 - Parallele Algorithmen in der STL"
        description:
        type: youtube
        video_id: "9VlNjHhKHMc"
        duration: 1188
