# https://www.youtube.com/playlist?list=PLNmsVeXQZj7oBz3PP5sGIkLnmBbw10UUP
title: "Lambda Kalkül"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665506696
sections:
  - id: section
    title: "Lambda Kalkül"
    description:
    lectures:
      - id: "KJmaND1V4r4"
        title: "Lambda Kalkül #1 - Einführung - Theoretische Informatik"
        description:
        type: youtube
        video_id: "KJmaND1V4r4"
        duration: 751
      - id: "CeU5CrvsPuw"
        title: "Lambda Kalkül #2 - Alpha-Äquivalenz - Theoretische Informatik"
        description:
        type: youtube
        video_id: "CeU5CrvsPuw"
        duration: 346
      - id: "9sFgP105EJg"
        title: "Lambda Kalkül #3 - Beta Reduktion - Theoretische Informatik"
        description:
        type: youtube
        video_id: "9sFgP105EJg"
        duration: 452
      - id: "rNmPopvqAzc"
        title: "Lambda Kalkül #4 - Normalreihenfolge und Normalform - Theoretische Informatik"
        description:
        type: youtube
        video_id: "rNmPopvqAzc"
        duration: 282
      - id: "LBLCiM34S6Q"
        title: "Lambda Kalkül #5 - Call-by-Name und Call-by-Value - Theoretische Informatik"
        description:
        type: youtube
        video_id: "LBLCiM34S6Q"
        duration: 335
      - id: "qx5h6-uLork"
        title: "Lambda Kalkül #6 - natürliche Zahlen - Church Zahlen - Theoretische Informatik"
        description:
        type: youtube
        video_id: "qx5h6-uLork"
        duration: 572
      - id: "L1YbhqcBXDw"
        title: "Lambda Kalkül #7 - Addition von Church-Zahlen - Theoretische Informatik"
        description:
        type: youtube
        video_id: "L1YbhqcBXDw"
        duration: 477
      - id: "dubTJQ-iGLk"
        title: "Lambda Kalkül #8 - Multiplikation von Church Zahlen - Theoretische Informatik"
        description:
        type: youtube
        video_id: "dubTJQ-iGLk"
        duration: 357
      - id: "r4V2fQv8y9g"
        title: "Lambda Kalkül #9 - True, False, If und AND - Theoretische Informatik"
        description:
        type: youtube
        video_id: "r4V2fQv8y9g"
        duration: 499
      - id: "xgQRhVQY3mM"
        title: "Lambda Kalkül #10 - Typsysteme - Theoretische Informatik"
        description:
        type: youtube
        video_id: "xgQRhVQY3mM"
        duration: 418
      - id: "dQnoxO4SQUI"
        title: "Lambda Kalkül #11 - Typsysteme: Abstraktionsregel - Theoretische Informatik"
        description:
        type: youtube
        video_id: "dQnoxO4SQUI"
        duration: 382
      - id: "raTfwW-A-PY"
        title: "Lambda Kalkül #12 - Typsysteme: Applikationsregel - Theoretische Informatik"
        description:
        type: youtube
        video_id: "raTfwW-A-PY"
        duration: 462
      - id: "mLt7PIypMvk"
        title: "Lambda Kalkül #13 - Typsysteme: Konstanten- und Variablenregel - Theoretische Informatik"
        description:
        type: youtube
        video_id: "mLt7PIypMvk"
        duration: 281
      - id: "F0x6_11fHqM"
        title: "Lambda Kalkül #14 - Typsysteme: variable Typen - Theoretische Informatik"
        description:
        type: youtube
        video_id: "F0x6_11fHqM"
        duration: 369
      - id: "ZL3kqMmMyZg"
        title: "Lambda Kalkül #15 - Typsysteme: Let Regel - Theoretische Informatik"
        description:
        type: youtube
        video_id: "ZL3kqMmMyZg"
        duration: 874
      - id: "FF-bmQBUzlM"
        title: "Lambda Kalkül #16 - Typsysteme: Ein Beispielbaum - Theoretische Informatik"
        description:
        type: youtube
        video_id: "FF-bmQBUzlM"
        duration: 726
      - id: "Bx6-OoYk6H0"
        title: "Lambda Kalkül #17 - Typsysteme: Unifikation - Theoretische Informatik"
        description:
        type: youtube
        video_id: "Bx6-OoYk6H0"
        duration: 747
