# https://www.dropbox.com/t/zSbvLhXHePo5x92u
title: "Pentesting Grundlagen"
description: |
  Hacker-Angriffe gibt es überall. Aber wie gehen Hacker wirklich vor? Was nutzen sie?
  Diese Serie fasst meine alten Playlists zu allgemeinem Pentesting zusammen - wird aber noch ergänzt, da ich mit vielem nicht mehr ganz so zufrieden bin und noch einiges fehlt!
category:
language: de
image: https://static.bootstrap.academy/thumbnails/pentesting.jpg
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665584088
sections:
  - id: section
    title: "Pre-Engagement"
    description:
    lectures:
      - id: "was_tun_hacker"
        title: "Was tun Hacker"
        description:
        type: mp4
        duration: 897
      - id: "pentesting_1_einleitung"
        title: "Was ist Pentesting?"
        description:
        type: mp4
        duration: 530
      - id: "pentesting_2_pre_engagement"
        title: "Pre-engagement"
        description:
        type: mp4
        duration: 646
  - id: section2
    title: "Information Gathering"
    description:
    lectures:
      - id: "pentesting_2_a_information_gathering"
        title: "Information Gathering"
        description:
        type: mp4
        duration: 398
      - id: "pentesting_3_welche_informationen_uns_ping_verschafft"
        title: "Welche Informationen uns Ping verschafft"
        description:
        type: mp4
        duration: 681
      - id: "pentesting_4_whois"
        title: "WHOIS"
        description:
        type: mp4
        duration: 248
      - id: "pentesting_5_dns_einträge"
        title: "DNS-Einträge"
        description:
        type: mp4
        duration: 290
      - id: "hacken_tutorial_dnsrecon"
        title: "DNSRecon"
        description:
        type: mp4
        duration: 459
      - id: "pentesting_6_http_reponse_headers"
        title: "HTTP-Reponse Headers"
        description:
        type: mp4
        duration: 426
      - id: "pentesting_7_google_hacking_database"
        title: "Google Hacking Database"
        description:
        type: mp4
        duration: 249
      - id: "pentesting_8_google_commands"
        title: "Google Commands"
        description:
        type: mp4
        duration: 552
      - id: "pentesting_9_the_harvester"
        title: "The Harvester"
        description:
        type: mp4
        duration: 251
      - id: "TV-uJHR5v-Q"
        title: "Überprüfen, ob eine Email Adresse auf dem Server existiert"
        description:
        type: youtube
        video_id: "TV-uJHR5v-Q"
        duration: 324
      - id: "pentesting_10_netcraft"
        title: "Netcraft"
        description:
        type: mp4
        duration: 242
      - id: "pentesting_11_port_scanning"
        title: "Port Scanning"
        description:
        type: mp4
        duration: 396
      - id: "EzKy7gDQh6A"
        title: "RustScan: Das schnellere nmap"
        description:
        type: youtube
        video_id: "EzKy7gDQh6A"
        duration: 393
      - id: "pentesting_12_port_scanning_arten"
        title: "Port Scanning Arten"
        description:
        type: mp4
        duration: 568
      - id: "pentesting_13_vulnerability_scanner"
        title: "Vulnerability Scanner"
        description:
        type: mp4
        duration: 382
      - id: "pentesting_14_input_fuzzing"
        title: "Input Fuzzing"
        description:
        type: mp4
        duration: 185
      - id: "GLmpLeghM2Y"
        title: "WLan angreifen - WPA/WPA2 über Handshake - Bruteforce"
        description:
        type: youtube
        video_id: "GLmpLeghM2Y"
        duration: 1103
      - id: "DltSGCQ4KWE"
        title: "WLan angreifen - WPS mit Reaver"
        description:
        type: youtube
        video_id: "DltSGCQ4KWE"
        duration: 746
      - id: "K0DkuJewt-s"
        title: "einen Evil Twin erstellen"
        description:
        type: youtube
        video_id: "K0DkuJewt-s"
        duration: 775
      - id: "hacking_4_sniffen_mit_einem_evil_twin"
        title: "Sniffen mit einem Evil Twin"
        description:
        type: mp4
        duration: 521
      - id: "hacking_5_macchanger"
        title: "Macchanger"
        description:
        type: mp4
        duration: 463
      - id: "lr9NnFqZlMo"
        title: "Dateien von Windows retten"
        description:
        type: youtube
        video_id: "lr9NnFqZlMo"
        duration: 303
      - id: "PlDg6vNSYnk"
        title: "Shodan - Suchengine für Hacker"
        description:
        type: youtube
        video_id: "PlDg6vNSYnk"
        duration: 171
      - id: "hacking_15_server_herausfinden_mit_netcat"
        title: "Server herausfinden mit Netcat"
        description:
        type: mp4
        duration: 190
      - id: "hacking_16_serveranalyse_mit_httprint"
        title: "Serveranalyse mit httprint"
        description:
        type: mp4
        duration: 316
      - id: "hacking_20_scans_mit_xprobe"
        title: "Scans mit xprobe"
        description:
        type: mp4
        duration: 135
      - id: "hacking_vulnerability_scans_mit_uniscan_mit_disclaimer"
        title: "Hacking Vulnerability Scans mit uniscan"
        description:
        type: mp4
        duration: 377
  - id: section3
    title: "Threat Modelling"
    description:
    lectures: []
  - id: section4
    title: "Vulnerability Analysis"
    description:
    lectures: []
  - id: section5
    title: "Exploitation"
    description:
    lectures:
      - id: "pentesting_15_zugriff_bekommen"
        title: "Zugriff bekommen"
        description:
        type: mp4
        duration: 432
      - id: "hacking_18_einen_socket_server_erstellen_mit_netcat"
        title: "Einen Socket Server erstellen mit Netcat"
        description:
        type: mp4
        duration: 178
      - id: "hacking_19_browser_hacken_mit_beef"
        title: "Browser Hacken mit beEF"
        description:
        type: mp4
        duration: 421
      - id: "hacking_14_dos_angriffe_unter_linux"
        title: "DoS Angriffe unter Linux"
        description:
        type: mp4
        duration: 284
      - id: "hacking_8_dos_angriffe_auf_router"
        title: "DoS - Angriffe auf Router"
        description:
        type: mp4
        duration: 426
      - id: "hacking_9_dos_mit_loic"
        title: "DoS mit LOIC"
        description:
        type: mp4
        duration: 352
      - id: "hacking_slowloris_ddos_tool"
        title: "Slowloris DDoS Tool"
        description:
        type: mp4
        duration: 265
      - id: "hacking_dns_spoofing_mit_ettercap_vollständig"
        title: "DNS Spoofing mit Ettercap"
        description:
        type: mp4
        duration: 595
      - id: "hacking_qr_codes_mit_disclaimer"
        title: "QR Codes"
        description:
        type: mp4
        duration: 229
      - id: "hacking_social_engineering_mail_fälschen_mit_disclaimer"
        title: "Hacking - Social Engineering - Mail fälschen mit Disclaimer"
        description:
        type: mp4
        duration: 375
  - id: section6
    title: "Einschub: Metasploit"
    description:
    lectures:
      - id: "metasploit_1_basics"
        title: "Basics"
        description:
        type: mp4
        duration: 346
      - id: "metasploit_2_armitage"
        title: "Armitage"
        description:
        type: mp4
        duration: 330
      - id: "metasploit_3_payload_generieren"
        title: "Payload generieren"
        description:
        type: mp4
        duration: 420
      - id: "metasploit_4_veil_evasion"
        title: "Veil-Evasion"
        description:
        type: mp4
        duration: 470
      - id: "metasploit_5_meterpreter_und_tokens"
        title: "Meterpreter und Tokens"
        description:
        type: mp4
        duration: 667
      - id: "metasploit_admin_rechte_erzwingen"
        title: "Admin Rechte erzwingen"
        description:
        type: mp4
        duration: 360
      - id: "metasploit_übers_internet"
        title: "Metasploit Übers Internet"
        description:
        type: mp4
        duration: 483
  - id: section7
    title: "Post Exploitation"
    description:
    lectures:
      - id: "metasploit_6_webcam_screenshot_und_keylogger"
        title: "Webcam, Screenshot und Keylogger"
        description:
        type: mp4
        duration: 557
      - id: "metasploit_7_adminrechte_erhalten"
        title: "Adminrechte erhalten"
        description:
        type: mp4
        duration: 321
      - id: "metasploit_8_sessions_die_windows_shell_und_eigene_skripte_ausführen"
        title: "Sessions, die Windows Shell und eigene Skripte ausführen"
        description:
        type: mp4
        duration: 341
      - id: "metasploit_9_antivirenschutz_abschießen_und_automatisches_verbinden_bei_neustart"
        title: "Antivirenschutz abschießen und Automatisches Verbinden bei Neustart"
        description:
        type: mp4
        duration: 442
  - id: section8
    title: "Reporting"
    description:
    lectures: []
