# https://www.youtube.com/playlist?list=PLNmsVeXQZj7onyAB57T0xqV2ZVSZOo79a
title: "Gemeinsamkeiten von Programmiersprachen"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665506634
sections:
  - id: section
    title: "Grundlagen der Programmierung"
    description:
    lectures:
      - id: "nVMlDghNcHg"
        title: "Einleitung"
        description:
        type: youtube
        video_id: "nVMlDghNcHg"
        duration: 384
      - id: "l7M7jG-d7c4"
        title: "Variablen und der Codefluss"
        description:
        type: youtube
        video_id: "l7M7jG-d7c4"
        duration: 602
      - id: "-UA65GBxEtI"
        title: "Integer - Ganzzahlen"
        description:
        type: youtube
        video_id: "-UA65GBxEtI"
        duration: 669
      - id: "j2YhHdfgmko"
        title: "Fließkommazahlen"
        description:
        type: youtube
        video_id: "j2YhHdfgmko"
        duration: 562
      - id: "oNpV4luYx2I"
        title: "Buchstaben - Character"
        description:
        type: youtube
        video_id: "oNpV4luYx2I"
        duration: 274
      - id: "Z3IRchso41A"
        title: "Kommentare"
        description:
        type: youtube
        video_id: "Z3IRchso41A"
        duration: 227
      - id: "yiXbAG2vrlg"
        title: "Arrays"
        description:
        type: youtube
        video_id: "yiXbAG2vrlg"
        duration: 490
      - id: "vtyBWsyRU-o"
        title: "Mehrdimensionale Arrays"
        description:
        type: youtube
        video_id: "vtyBWsyRU-o"
        duration: 528
      - id: "EgleYPhgUU4"
        title: "Listen"
        description:
        type: youtube
        video_id: "EgleYPhgUU4"
        duration: 585
      - id: "Am0YUgyOybM"
        title: "Strings"
        description:
        type: youtube
        video_id: "Am0YUgyOybM"
        duration: 568
      - id: "GEjfGiVCvfs"
        title: "arithmetische Operatoren"
        description:
        type: youtube
        video_id: "GEjfGiVCvfs"
        duration: 647
      - id: "8EdMk4VKXdA"
        title: "if - Verzweigungen"
        description:
        type: youtube
        video_id: "8EdMk4VKXdA"
        duration: 572
      - id: "vGS1u9Ioy-g"
        title: "Booleans und Vergleichsoperatoren"
        description:
        type: youtube
        video_id: "vGS1u9Ioy-g"
        duration: 399
      - id: "UehOgM4D914"
        title: "logische Operatoren"
        description:
        type: youtube
        video_id: "UehOgM4D914"
        duration: 540
      - id: "K0kgwBMGSjg"
        title: "bitweise Operatoren"
        description:
        type: youtube
        video_id: "K0kgwBMGSjg"
        duration: 832
      - id: "PKHf-KQLp2s"
        title: "while Schleifen"
        description:
        type: youtube
        video_id: "PKHf-KQLp2s"
        duration: 455
      - id: "BFuzKat5gL0"
        title: "Die for-Schleife"
        description:
        type: youtube
        video_id: "BFuzKat5gL0"
        duration: 482
      - id: "JqKw80YDuVI"
        title: "foreach Schleifen"
        description:
        type: youtube
        video_id: "JqKw80YDuVI"
        duration: 278
      - id: "DSO4ITu9nYI"
        title: "break und continue"
        description:
        type: youtube
        video_id: "DSO4ITu9nYI"
        duration: 431
  - id: section2
    title: "Einführung in die funktionale Programmierung"
    description:
    lectures:
      - id: "F1AGkBrQnXU"
        title: "Funktionen"
        description:
        type: youtube
        video_id: "F1AGkBrQnXU"
        duration: 501
      - id: "KlSubMpETSg"
        title: "Rückgabewerte"
        description:
        type: youtube
        video_id: "KlSubMpETSg"
        duration: 562
      - id: "M_s3j6oYMfc"
        title: "Parameter"
        description:
        type: youtube
        video_id: "M_s3j6oYMfc"
        duration: 425
      - id: "4dut6s0E1vs"
        title: "Rekursion"
        description:
        type: youtube
        video_id: "4dut6s0E1vs"
        duration: 589
      - id: "jL-2n9wkMfs"
        title: "Default Argumente"
        description:
        type: youtube
        video_id: "jL-2n9wkMfs"
        duration: 249
      - id: "-_oHc7YtF54"
        title: "Call-by-Value vs Call-by-Reference"
        description:
        type: youtube
        video_id: "-_oHc7YtF54"
        duration: 703
      - id: "XaFU2JHcWM4"
        title: "Lazy Evaluation"
        description:
        type: youtube
        video_id: "XaFU2JHcWM4"
        duration: 398
      - id: "KcIlkkOcGwQ"
        title: "Funktionen sind auch nur Variablen - Function Pointer"
        description:
        type: youtube
        video_id: "KcIlkkOcGwQ"
        duration: 365
      - id: "MZKVP6wNYuA"
        title: "Lambda Funktionen"
        description:
        type: youtube
        video_id: "MZKVP6wNYuA"
        duration: 292
      - id: "jlvKo3eFKD4"
        title: "Inline Funktionen"
        description:
        type: youtube
        video_id: "jlvKo3eFKD4"
        duration: 799
      - id: "dDKmkOjcaZE"
        title: "Code lesen - wie wird's gemacht"
        description:
        type: youtube
        video_id: "dDKmkOjcaZE"
        duration: 1078
  - id: section3
    title: "Einführung in die objektorientierte Programmierung"
    description:
    lectures:
      - id: "MIKUT5mvtcE"
        title: "Klassen"
        description:
        type: youtube
        video_id: "MIKUT5mvtcE"
        duration: 610
      - id: "2oIXNBn-1ik"
        title: "Methoden"
        description:
        type: youtube
        video_id: "2oIXNBn-1ik"
        duration: 411
      - id: "sZoyPJK6cB0"
        title: "Konstruktoren"
        description:
        type: youtube
        video_id: "sZoyPJK6cB0"
        duration: 499
      - id: "mmLpVW5uToI"
        title: "Zugriffsmodifikatoren"
        description:
        type: youtube
        video_id: "mmLpVW5uToI"
        duration: 605
      - id: "aO4leORLrek"
        title: "Static - Klassenvariablen"
        description:
        type: youtube
        video_id: "aO4leORLrek"
        duration: 415
      - id: "gt3FV9YhTts"
        title: "Vererbung"
        description:
        type: youtube
        video_id: "gt3FV9YhTts"
        duration: 494
      - id: "2TA-Gcs5XFs"
        title: "TypeCasts"
        description:
        type: youtube
        video_id: "2TA-Gcs5XFs"
        duration: 543
      - id: "3k3Pq3pJlHo"
        title: "instanceof und typeof"
        description:
        type: youtube
        video_id: "3k3Pq3pJlHo"
        duration: 268
      - id: "gDXHBqRJ3lM"
        title: "Überschreiben von Methoden"
        description:
        type: youtube
        video_id: "gDXHBqRJ3lM"
        duration: 329
  - id: section4
    title: "Fortgeschrittene Objektorientierung"
    description:
    lectures:
      - id: "Rcnai3U0RcE"
        title: "Enums"
        description:
        type: youtube
        video_id: "Rcnai3U0RcE"
        duration: 227
      - id: "pqwBUimLMYY"
        title: "Operatoren überschreiben"
        description:
        type: youtube
        video_id: "pqwBUimLMYY"
        duration: 376
      - id: "Ktfjm9caHxc"
        title: "Super"
        description:
        type: youtube
        video_id: "Ktfjm9caHxc"
        duration: 351
      - id: "nj7YcDQvTHU"
        title: "Interfaces"
        description:
        type: youtube
        video_id: "nj7YcDQvTHU"
        duration: 447
      - id: "pnyTVFITVoY"
        title: "Mehrfachvererbung und das Diamantenproblem"
        description:
        type: youtube
        video_id: "pnyTVFITVoY"
        duration: 424
      - id: "ofkuSg6dUf4"
        title: "Abstrakte Klassen"
        description:
        type: youtube
        video_id: "ofkuSg6dUf4"
        duration: 298
      - id: "8UKrmsB4DiY"
        title: "Der Zugriffsmodifikator protected"
        description:
        type: youtube
        video_id: "8UKrmsB4DiY"
        duration: 195
      - id: "Pmz_M92miP8"
        title: "statische innere Klassen"
        description:
        type: youtube
        video_id: "Pmz_M92miP8"
        duration: 478
      - id: "b3V73ya2FS0"
        title: "innere Klassen"
        description:
        type: youtube
        video_id: "b3V73ya2FS0"
        duration: 359
      - id: "VET4R9hd5ks"
        title: "anonyme innere Klassen"
        description:
        type: youtube
        video_id: "VET4R9hd5ks"
        duration: 257
      - id: "Da2J0exYRN0"
        title: "Module"
        description:
        type: youtube
        video_id: "Da2J0exYRN0"
        duration: 417
      - id: "zDxv2kI575Q"
        title: "Dynamic vs Static Scoping"
        description:
        type: youtube
        video_id: "zDxv2kI575Q"
        duration: 460
      - id: "TWcosPyPfrY"
        title: "Mixins"
        description:
        type: youtube
        video_id: "TWcosPyPfrY"
        duration: 301
  - id: section5
    title: "Generische Objektorientierung"
    description:
    lectures:
      - id: "Bfr0-t7lXVs"
        title: "Generics"
        description:
        type: youtube
        video_id: "Bfr0-t7lXVs"
        duration: 516
      - id: "w43Mhmr1_ec"
        title: "generische Funktionen"
        description:
        type: youtube
        video_id: "w43Mhmr1_ec"
        duration: 575
      - id: "tcj7g_Q9Wnc"
        title: "Typschranken"
        description:
        type: youtube
        video_id: "tcj7g_Q9Wnc"
        duration: 304
  - id: section6
    title: "Einführung in die objektorientierte Programmierung"
    description:
    lectures:
      - id: "d50Nir52aS8"
        title: "Prozesse vs Threads"
        description:
        type: youtube
        video_id: "d50Nir52aS8"
        duration: 702
      - id: "OzyV_tTlcZg"
        title: "Threads erstellen"
        description:
        type: youtube
        video_id: "OzyV_tTlcZg"
        duration: 461
      - id: "5AYVw_YokEI"
        title: "Nebenläufigkeit von Threads"
        description:
        type: youtube
        video_id: "5AYVw_YokEI"
        duration: 328
      - id: "8aNB2O9BtRU"
        title: "Atomare Operationen"
        description:
        type: youtube
        video_id: "8aNB2O9BtRU"
        duration: 334
      - id: "AdzCb97qqRY"
        title: "synchronized und locks"
        description:
        type: youtube
        video_id: "AdzCb97qqRY"
        duration: 451
      - id: "p2OEUX8tzLE"
        title: "Semaphoren"
        description:
        type: youtube
        video_id: "p2OEUX8tzLE"
        duration: 154
      - id: "uy5X4iXFLD0"
        title: "Deadlocks"
        description:
        type: youtube
        video_id: "uy5X4iXFLD0"
        duration: 414
      - id: "l-OOim0p3bE"
        title: "Concurrent Programming Languages"
        description:
        type: youtube
        video_id: "l-OOim0p3bE"
        duration: 374
      - id: "ThAU874F3cs"
        title: "Actors und Message Passing"
        description:
        type: youtube
        video_id: "ThAU874F3cs"
        duration: 349
      - id: "fjlotlmfH7U"
        title: "Programmieren Lernen #65 - Events"
        description:
        type: youtube
        video_id: "fjlotlmfH7U"
        duration: 322
      - id: "z6DQQhlQrI0"
        title: "Event Driven Development"
        description:
        type: youtube
        video_id: "z6DQQhlQrI0"
        duration: 401
  - id: section7
    title: "Debugging"
    description:
    lectures:
      - id: "t65-68pBfRA"
        title: "Debugging und Breakpoints"
        description:
        type: youtube
        video_id: "t65-68pBfRA"
        duration: 594
      - id: "RhNBE6o7tJU"
        title: "Testen"
        description:
        type: youtube
        video_id: "RhNBE6o7tJU"
        duration: 867
      - id: "f231K1LjKMU"
        title: "Exceptions"
        description:
        type: youtube
        video_id: "f231K1LjKMU"
        duration: 599
      - id: "cL8xtQ1_6HU"
        title: "eigene Exceptions"
        description:
        type: youtube
        video_id: "cL8xtQ1_6HU"
        duration: 484
  - id: section8
    title: "Best Practice"
    description:
    lectures:
      - id: "EZ1atCGFhjw"
        title: "RegEx - Reguläre Ausdrücke"
        description:
        type: youtube
        video_id: "EZ1atCGFhjw"
        duration: 761
      - id: "kubXOU01Ws8"
        title: "Vektoren"
        description:
        type: youtube
        video_id: "kubXOU01Ws8"
        duration: 482
      - id: "_LF3yUium9o"
        title: "Zufall"
        description:
        type: youtube
        video_id: "_LF3yUium9o"
        duration: 524
      - id: "TrOk3FNv-8c"
        title: "Dateien"
        description:
        type: youtube
        video_id: "TrOk3FNv-8c"
        duration: 716
      - id: "RMS9WGEpBzI"
        title: "Dateien - Modi"
        description:
        type: youtube
        video_id: "RMS9WGEpBzI"
        duration: 498
      - id: "pjGctthnDXI"
        title: "Ascii und Unicode"
        description:
        type: youtube
        video_id: "pjGctthnDXI"
        duration: 487
      - id: "-_OEWwkJNqQ"
        title: "Binäre Dateien"
        description:
        type: youtube
        video_id: "-_OEWwkJNqQ"
        duration: 299
      - id: "RM4oMOuzkEA"
        title: "Objekt Serialisierung"
        description:
        type: youtube
        video_id: "RM4oMOuzkEA"
        duration: 337
      - id: "GRKkyF6Bkok"
        title: "XML und JSON"
        description:
        type: youtube
        video_id: "GRKkyF6Bkok"
        duration: 627
      - id: "ED4nCctxfDo"
        title: "Flushing"
        description:
        type: youtube
        video_id: "ED4nCctxfDo"
        duration: 287
      - id: "9H5INP4TNj8"
        title: "Absolute und Relative Pfade"
        description:
        type: youtube
        video_id: "9H5INP4TNj8"
        duration: 578
      - id: "pHMHbI4cI6o"
        title: "Logging"
        description:
        type: youtube
        video_id: "pHMHbI4cI6o"
        duration: 448
      - id: "e73Bxm4HsAs"
        title: "Datum und Uhrzeit"
        description:
        type: youtube
        video_id: "e73Bxm4HsAs"
        duration: 857
      - id: "RFT1ioXYm-U"
        title: "Networking"
        description:
        type: youtube
        video_id: "RFT1ioXYm-U"
        duration: 734
      - id: "Dcf0Ag49c38"
        title: "Datenbanken"
        description:
        type: youtube
        video_id: "Dcf0Ag49c38"
        duration: 892
  - id: section9
    title: "Fortgeschrittene Funktionale Programmierung"
    description:
    lectures:
      - id: "39GU7sZZrZA"
        title: "Inferierte Typen"
        description:
        type: youtube
        video_id: "39GU7sZZrZA"
        duration: 226
      - id: "4NCeP9yclZM"
        title: "Typinferenz von Funktionen"
        description:
        type: youtube
        video_id: "4NCeP9yclZM"
        duration: 461
      - id: "dUKIbPcXuyU"
        title: "Funktionen höherer Ordnung und Currying"
        description:
        type: youtube
        video_id: "dUKIbPcXuyU"
        duration: 564
      - id: "eDOF0B6H2G4"
        title: "Pattern Matching mit Listen"
        description:
        type: youtube
        video_id: "eDOF0B6H2G4"
        duration: 323
      - id: "1VIM4rml9BA"
        title: "Wildcards im Pattern Matching"
        description:
        type: youtube
        video_id: "1VIM4rml9BA"
        duration: 167
      - id: "HoSWY0uK7to"
        title: "Pattern Guards"
        description:
        type: youtube
        video_id: "HoSWY0uK7to"
        duration: 148
      - id: "bxsCzFHZrow"
        title: "Case Classes"
        description:
        type: youtube
        video_id: "bxsCzFHZrow"
        duration: 277
      - id: "u5YWnmcTsn0"
        title: "Map"
        description:
        type: youtube
        video_id: "u5YWnmcTsn0"
        duration: 332
      - id: "nVE68kbRypA"
        title: "Zip"
        description:
        type: youtube
        video_id: "nVE68kbRypA"
        duration: 321
      - id: "M9-Scj76TTw"
        title: "Unzip"
        description:
        type: youtube
        video_id: "M9-Scj76TTw"
        duration: 127
      - id: "eGhe755ryK8"
        title: "Filter"
        description:
        type: youtube
        video_id: "eGhe755ryK8"
        duration: 246
      - id: "r6rRP5q1fTU"
        title: "Reduce"
        description:
        type: youtube
        video_id: "r6rRP5q1fTU"
        duration: 520
      - id: "sdlQOyvKde8"
        title: "Generatoren"
        description:
        type: youtube
        video_id: "sdlQOyvKde8"
        duration: 342
      - id: "ZRJ5BaSBQ8Q"
        title: "Dekoratoren"
        description:
        type: youtube
        video_id: "ZRJ5BaSBQ8Q"
        duration: 363
      - id: "VobBC97dXcI"
        title: "List Comprehensions"
        description:
        type: youtube
        video_id: "VobBC97dXcI"
        duration: 418
