# https://www.youtube.com/playlist?list=PLNmsVeXQZj7q7ODiEAnq2EnsP-8LMGtfw
title: "Prolog: Logische Programmierung"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665506685
sections:
  - id: section
    title: "Prolog Programmierung"
    description:
    lectures:
      - id: "8iUYNp5Z45o"
        title: "Einführung"
        description:
        type: youtube
        video_id: "8iUYNp5Z45o"
        duration: 485
      - id: "9bCzsE-LamI"
        title: "Regeln"
        description:
        type: youtube
        video_id: "9bCzsE-LamI"
        duration: 569
      - id: "hpQYxISZC74"
        title: "Die Großeltern von Robb Stark"
        description:
        type: youtube
        video_id: "hpQYxISZC74"
        duration: 723
      - id: "DZeeXgOEjzs"
        title: "Listen"
        description:
        type: youtube
        video_id: "DZeeXgOEjzs"
        duration: 772
      - id: "gyPChcbuok8"
        title: "Zuweisungen"
        description:
        type: youtube
        video_id: "gyPChcbuok8"
        duration: 426
      - id: "tRYRwmkH9bA"
        title: "Cuts"
        description:
        type: youtube
        video_id: "tRYRwmkH9bA"
        duration: 516
      - id: "-TxFZmCq_no"
        title: "Send + More = Money"
        description:
        type: youtube
        video_id: "-TxFZmCq_no"
        duration: 770
