# https://www.youtube.com/playlist?list=PLNmsVeXQZj7p09TLbRQmqzbH81DHjBO8E
title: "Python Let's Code"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665506553
sections:
  - id: section
    title: "Python Let's Code"
    description:
    lectures:
      - id: "wI9yE7ZIbMg"
        title: "Wasserzeichen und Komprimieren von Bildern"
        description:
        type: youtube
        video_id: "wI9yE7ZIbMg"
        duration: 1015
      - id: "J5CEZ1lZo_o"
        title: "Stable Diffusion: Besser als Dall E 2 in Python [Tutorial]"
        description:
        type: youtube
        video_id: "J5CEZ1lZo_o"
        duration: 1083
      - id: "vXrBTD8adW0"
        title: "Eine Website für Stable Diffusion"
        description:
        type: youtube
        video_id: "vXrBTD8adW0"
        duration: 928
      - id: "NvH6StJ918s"
        title: "Mit Python Personen auf Bildern identifizieren"
        description:
        type: youtube
        video_id: "NvH6StJ918s"
        duration: 1408
      - id: "aFYxOS96q2A"
        title: "BEAT THE TRÖTE"
        description:
        type: youtube
        video_id: "aFYxOS96q2A"
        duration: 920
      - id: "zwiKIzvGAhM"
        title: "Gesichtserkennung mit Python und OpenCV in 14 Zeilen"
        description:
        type: youtube
        video_id: "zwiKIzvGAhM"
        duration: 695
      - id: "fflEcVtGSlE"
        title: "PyScript - Python im Browser als JavaScript-Ersatz"
        description:
        type: youtube
        video_id: "fflEcVtGSlE"
        duration: 1098
      - id: "ZOWLCEJzQPQ"
        title: "Ein Zufallsgenerator mit Lavalampe und Python"
        description:
        type: youtube
        video_id: "ZOWLCEJzQPQ"
        duration: 1470
      - id: "RRuU0W6_kso"
        title: "Graphen"
        description:
        type: youtube
        video_id: "RRuU0W6_kso"
        duration: 954
      - id: "soVqW_yoKIU"
        title: "Graphen zeichnen"
        description:
        type: youtube
        video_id: "soVqW_yoKIU"
        duration: 618
      - id: "Gc92z58-Qm4"
        title: "Snake in Python in unter 150 Zeilen Code [PyGame]"
        description:
        type: youtube
        video_id: "Gc92z58-Qm4"
        duration: 3709
      - id: "1HxjDXykSmc"
        title: "FTP steuern und verwalten mit FTPlib"
        description:
        type: youtube
        video_id: "1HxjDXykSmc"
        duration: 1324
      - id: "XkvcUlvGqvs"
        title: "SECURE FTP - SFTP mit pysftp"
        description:
        type: youtube
        video_id: "XkvcUlvGqvs"
        duration: 1148
      - id: "sj03Q-JYZqA"
        title: "2FA One Time Passwords mit PyOTP"
        description:
        type: youtube
        video_id: "sj03Q-JYZqA"
        duration: 853
      - id: "VVKFuZf9jNw"
        title: "Passwörter sicher speichern"
        description:
        type: youtube
        video_id: "VVKFuZf9jNw"
        duration: 1140
      - id: "dipFOn4kZHY"
        title: "Text \"Clean\" machen"
        description:
        type: youtube
        video_id: "dipFOn4kZHY"
        duration: 1531
      - id: "cnrhMjroWrI"
        title: "Größe eines Verzeichnisses berechnen"
        description:
        type: youtube
        video_id: "cnrhMjroWrI"
        duration: 717
      - id: "0q9CLHGV1Fo"
        title: "Schrift in Bildern erkennen und in Text umwandeln mit PyTesseract"
        description:
        type: youtube
        video_id: "0q9CLHGV1Fo"
        duration: 737
      - id: "-XXj-uLdGmQ"
        title: "Webcam nutzen und Kanten erkennen"
        description:
        type: youtube
        video_id: "-XXj-uLdGmQ"
        duration: 682
      - id: "lWDWJaV_rZ4"
        title: "Subdomains einer Website enumerieren"
        description:
        type: youtube
        video_id: "lWDWJaV_rZ4"
        duration: 583
      - id: "m9U2WrmtfR4"
        title: "CSGO Cheats, Code Injection & mehr: So wird Python Code in ausführbare Dateien migriert"
        description:
        type: youtube
        video_id: "m9U2WrmtfR4"
        duration: 627
      - id: "NcDlSAObptE"
        title: "Ein Python VideoPlayer mit PyGame und Moviepy"
        description:
        type: youtube
        video_id: "NcDlSAObptE"
        duration: 323
      - id: "iLg9KSFxzi8"
        title: "Das TOR-Netzwerk mit Python nutzen (via TorPy)"
        description:
        type: youtube
        video_id: "iLg9KSFxzi8"
        duration: 1198
      - id: "bFlyT4cDXew"
        title: "Alle Bilder einer Website runterladen"
        description:
        type: youtube
        video_id: "bFlyT4cDXew"
        duration: 628
      - id: "9YBaUXzvBOo"
        title: "Mit Python QR Codes erstellen und einlesen"
        description:
        type: youtube
        video_id: "9YBaUXzvBOo"
        duration: 568
      - id: "JG1CC89mF00"
        title: "Ein Prozessmonitor mit Python"
        description:
        type: youtube
        video_id: "JG1CC89mF00"
        duration: 1157
      - id: "6Sf_qHehLgU"
        title: "Ein einfacher Screenrecorder in Python mit opencv und pyautogui"
        description:
        type: youtube
        video_id: "6Sf_qHehLgU"
        duration: 766
      - id: "TZJQoi1h2FI"
        title: "Text-To-Speech in Python in 4 Zeilen"
        description:
        type: youtube
        video_id: "TZJQoi1h2FI"
        duration: 230
      - id: "OZo2HxoIOtw"
        title: "PDF Dateien zusammenfügen, trennen und Text auslesen mit Python"
        description:
        type: youtube
        video_id: "OZo2HxoIOtw"
        duration: 1028
      - id: "uZ9WWzkH17I"
        title: "Mit RSA Text verschlüsseln in Python [PyCryptodome]"
        description:
        type: youtube
        video_id: "uZ9WWzkH17I"
        duration: 1308
      - id: "P4F2Zt25j2I"
        title: "Dateien verschlüsseln mit Python [PyCryptodome]"
        description:
        type: youtube
        video_id: "P4F2Zt25j2I"
        duration: 1816
      - id: "QthP_kxOy9Y"
        title: "Dateien über das Netzwerk verschicken mit Python [Sockets]"
        description:
        type: youtube
        video_id: "QthP_kxOy9Y"
        duration: 1164
      - id: "csPfQnCc9P0"
        title: "Sichere Passwörter erstellen mit Python"
        description:
        type: youtube
        video_id: "csPfQnCc9P0"
        duration: 583
      - id: "QBmhMpNAG0I"
        title: "Mein neues System - Systeminfo auslesen mit Python"
        description:
        type: youtube
        video_id: "QBmhMpNAG0I"
        duration: 1295
      - id: "SfPWCKTHzE4"
        title: "Tetris in Python in unter 250 Zeilen Code [PyGame]"
        description:
        type: youtube
        video_id: "SfPWCKTHzE4"
        duration: 5625
      - id: "Lb3fGHLLhL8"
        title: "Live Coding einer Blockchain in Python [Level: 7/10] zum Jubiläum des Community Projekts"
        description:
        type: youtube
        video_id: "Lb3fGHLLhL8"
        duration: 13972
      - id: "MP8lMbgv1Ls"
        title: "DNS Performancetest in Python"
        description:
        type: youtube
        video_id: "MP8lMbgv1Ls"
        duration: 873
