# https://www.youtube.com/playlist?list=PLNmsVeXQZj7otfP2zTa8AIiNIWVg0BRqs
title: "APIs programmieren mit Python Flask"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665507927
sections:
  - id: section
    title: "APIs programmieren mit Python Flask"
    description:
    lectures:
      - id: "EGYpNQ3GL1Y"
        title: "Python Flask Tutorial #0 - Flask vs. Django"
        description:
        type: youtube
        video_id: "EGYpNQ3GL1Y"
        duration: 336
      - id: "I0KSJKHuHe4"
        title: "Python Flask Tutorial #1 - Installation"
        description:
        type: youtube
        video_id: "I0KSJKHuHe4"
        duration: 374
      - id: "EMcTreG8N3g"
        title: "Python Flask Tutorial #2 - Routing"
        description:
        type: youtube
        video_id: "EMcTreG8N3g"
        duration: 217
      - id: "x0iLkYsoWTU"
        title: "Python Flask Tutorial #3 - Variable Routen"
        description:
        type: youtube
        video_id: "x0iLkYsoWTU"
        duration: 461
      - id: "kKixgYl_eIM"
        title: "Python Flask Tutorial #4 - URLs generieren"
        description:
        type: youtube
        video_id: "kKixgYl_eIM"
        duration: 217
      - id: "BOKYL5vfQX4"
        title: "Python Flask Tutorial #5 - HTTP GET und POST"
        description:
        type: youtube
        video_id: "BOKYL5vfQX4"
        duration: 585
      - id: "bF6JCnRtE2Q"
        title: "Python Flask Tutorial #6 - Templates"
        description:
        type: youtube
        video_id: "bF6JCnRtE2Q"
        duration: 196
      - id: "Grr7g_dDveE"
        title: "Python Flask Tutorial #7 - Templates mit Parametern und Code"
        description:
        type: youtube
        video_id: "Grr7g_dDveE"
        duration: 491
      - id: "sc54UH2rOgs"
        title: "Python Flask Tutorial #8 - Dateiuploads"
        description:
        type: youtube
        video_id: "sc54UH2rOgs"
        duration: 821
      - id: "w5CgRaBVZ7c"
        title: "Python Flask Tutorial #9 - Cookies"
        description:
        type: youtube
        video_id: "w5CgRaBVZ7c"
        duration: 351
      - id: "GgS8-mn9zoM"
        title: "Python Flask Tutorial #10 - Sessions"
        description:
        type: youtube
        video_id: "GgS8-mn9zoM"
        duration: 737
      - id: "ZgwHvNCn3QQ"
        title: "Python Flask Tutorial #11 - Kurze Einführung in Datenbanken mit python"
        description:
        type: youtube
        video_id: "ZgwHvNCn3QQ"
        duration: 462
      - id: "K6LuzmG1Anw"
        title: "Python Flask Tutorial #12 - SSL"
        description:
        type: youtube
        video_id: "K6LuzmG1Anw"
        duration: 424
      - id: "8UJTSQEcKgA"
        title: "Python Flask Tutorial #13 - Threaded Apps [German/Deutsch]"
        description:
        type: youtube
        video_id: "8UJTSQEcKgA"
        duration: 165
      - id: "r-y72UeF-4U"
        title: "Python Flask Tutorial #14 - Fehlermeldungen"
        description:
        type: youtube
        video_id: "r-y72UeF-4U"
        duration: 283
      - id: "ZebnoIOdZLI"
        title: "Python Flask Tutorial #15 - Logging [German/Deutsch]"
        description:
        type: youtube
        video_id: "ZebnoIOdZLI"
        duration: 283
      - id: "AKD5RZQl5Y4"
        title: "Python Flask Tutorial #16 - Json empfangen"
        description:
        type: youtube
        video_id: "AKD5RZQl5Y4"
        duration: 706
      - id: "uD-7KvlxLmY"
        title: "Python Flask Tutorial #17 - Catch All URLs [German/Deutsch]"
        description:
        type: youtube
        video_id: "uD-7KvlxLmY"
        duration: 161
      - id: "hqhc2Wxq3W4"
        title: "Python Flask Tutorial #18 - HTTP Authentifikation"
        description:
        type: youtube
        video_id: "hqhc2Wxq3W4"
        duration: 719
      - id: "sIODSMgqHIE"
        title: "Python Flask Tutorial #19 - Unittests"
        description:
        type: youtube
        video_id: "sIODSMgqHIE"
        duration: 640
      - id: "0-R7_Q9GtzE"
        title: "Python Flask Tutorial #20 - Eine RESTful-API mit RESTplus #1 - Projekteinleitung"
        description:
        type: youtube
        video_id: "0-R7_Q9GtzE"
        duration: 475
      - id: "GmHEZ8ipZiE"
        title: "Python Flask Tutorial #21 - App Konfiguration für die Nutzung von Swagger"
        description:
        type: youtube
        video_id: "GmHEZ8ipZiE"
        duration: 513
      - id: "kTpkzGDVclw"
        title: "Python Flask Tutorial #22 - Blueprints"
        description:
        type: youtube
        video_id: "kTpkzGDVclw"
        duration: 304
      - id: "O4Kze2oUauw"
        title: "Python Flask Tutorial #23 - API-Definitionen mit restplus"
        description:
        type: youtube
        video_id: "O4Kze2oUauw"
        duration: 511
      - id: "uV5s7t0OsP4"
        title: "Python Flask Tutorial #24 - Namespaces"
        description:
        type: youtube
        video_id: "uV5s7t0OsP4"
        duration: 442
      - id: "C8KFZNL90m8"
        title: "Python Flask Tutorial #25 - Klassen für Routen"
        description:
        type: youtube
        video_id: "C8KFZNL90m8"
        duration: 473
      - id: "YvXHpBYH4yE"
        title: "Python Flask Tutorial #26 - API Models"
        description:
        type: youtube
        video_id: "YvXHpBYH4yE"
        duration: 871
      - id: "jV5_eA8eKHU"
        title: "Python Flask Tutorial #27 - Flasks Argument-Parser"
        description:
        type: youtube
        video_id: "jV5_eA8eKHU"
        duration: 431
      - id: "2ZDfHRu2IeA"
        title: "Python Flask Tutorial #28 - Die Domain Logik"
        description:
        type: youtube
        video_id: "2ZDfHRu2IeA"
        duration: 312
      - id: "Fkt2TQ1MdSA"
        title: "Python Flask Tutorial #29 - Die Data Transfer Objects"
        description:
        type: youtube
        video_id: "Fkt2TQ1MdSA"
        duration: 311
      - id: "aH647Ex5lgA"
        title: "Python Flask Tutorial #30 - SQLAlchemy"
        description:
        type: youtube
        video_id: "aH647Ex5lgA"
        duration: 437
      - id: "jw-KOnrtMEE"
        title: "Python Flask Tutorial #31 - Die API-Endpoints"
        description:
        type: youtube
        video_id: "jw-KOnrtMEE"
        duration: 248
      - id: "CduKJ75SMl0"
        title: "Python Flask Tutorial #32 - kurze Fehlerbehebung"
        description:
        type: youtube
        video_id: "CduKJ75SMl0"
        duration: 480
      - id: "NUDZKqBpQTY"
        title: "Python Flask Tutorial #33 - einzelne Items"
        description:
        type: youtube
        video_id: "NUDZKqBpQTY"
        duration: 344
      - id: "R6iFm-OUpcE"
        title: "Python Flask Tutorial #34 - die automatische Swagger UI Integration"
        description:
        type: youtube
        video_id: "R6iFm-OUpcE"
        duration: 421
      - id: "a5-83uboWzs"
        title: "JSON Web Tokens"
        description:
        type: youtube
        video_id: "a5-83uboWzs"
        duration: 876
      - id: "_bwgJFVY2zY"
        title: "Flask - JSON Web Tokens - JWT Extended [German/Deutsch]"
        description:
        type: youtube
        video_id: "_bwgJFVY2zY"
        duration: 1378
      - id: "yB3048KZswc"
        title: "Python Flask Tutorial - Deployment"
        description:
        type: youtube
        video_id: "yB3048KZswc"
        duration: 350
