# https://www.youtube.com/playlist?list=PLNmsVeXQZj7qNMn6zimfu4JPUklG-4Uu4
title: "Softwareengineering - Wie entwickelt man Software"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665507210
sections:
  - id: section
    title: "Softwareengineering - Wie entwickelt man Software"
    description:
    lectures:
      - id: "r4u_6OPHiMo"
        title: "Softwareengineering Tutorial #1 - Einleitung"
        description:
        type: youtube
        video_id: "r4u_6OPHiMo"
        duration: 747
      - id: "TgXV_Lw-dBo"
        title: "Softwareengineering Tutorial #2 - Das Wasserfallmodell"
        description:
        type: youtube
        video_id: "TgXV_Lw-dBo"
        duration: 400
      - id: "GZjdl_zf4LA"
        title: "Softwareengineering Tutorial #3 - Scrum"
        description:
        type: youtube
        video_id: "GZjdl_zf4LA"
        duration: 941
      - id: "Q4a519zKeyg"
        title: "Softwareengineering Tutorial #4 - Projektfindung"
        description:
        type: youtube
        video_id: "Q4a519zKeyg"
        duration: 272
      - id: "v3zzvFv1gME"
        title: "Softwareengineering Tutorial #5 - Die Planungsphase"
        description:
        type: youtube
        video_id: "v3zzvFv1gME"
        duration: 459
      - id: "m5deYfB4Zn8"
        title: "Softwareengineering Tutorial #6 - Requirements: Kategorien"
        description:
        type: youtube
        video_id: "m5deYfB4Zn8"
        duration: 380
      - id: "kTeEIdSd7-o"
        title: "Softwareengineering Tutorial #7 - Der Entwurf"
        description:
        type: youtube
        video_id: "kTeEIdSd7-o"
        duration: 300
      - id: "PdlP8gzpRyo"
        title: "UML Tutorial #1 - Einleitung"
        description:
        type: youtube
        video_id: "PdlP8gzpRyo"
        duration: 718
      - id: "F5k1u5mzZ3U"
        title: "UML Tutorial #2 - Klassendiagrammen Intro"
        description:
        type: youtube
        video_id: "F5k1u5mzZ3U"
        duration: 475
      - id: "fQZOFYuLd-k"
        title: "UML Tutorial #3 - Vererbung"
        description:
        type: youtube
        video_id: "fQZOFYuLd-k"
        duration: 601
      - id: "fO7YTqZWZNQ"
        title: "UML Tutorial #4 - Assoziationen"
        description:
        type: youtube
        video_id: "fO7YTqZWZNQ"
        duration: 491
      - id: "JvJjOZR6q9s"
        title: "UML Tutorial #5 - Assoziationsklassen"
        description:
        type: youtube
        video_id: "JvJjOZR6q9s"
        duration: 234
      - id: "WKKZo1tiOy0"
        title: "UML Tutorial #6 - Aggregationen"
        description:
        type: youtube
        video_id: "WKKZo1tiOy0"
        duration: 259
      - id: "uSrBTr7d_g8"
        title: "UML Tutorial #7 - reflexive Assoziationen"
        description:
        type: youtube
        video_id: "uSrBTr7d_g8"
        duration: 504
      - id: "7sluwA4RSoU"
        title: "UML Tutorial #8 - OCL - Object Constraint Language [GERMAN/DEUTSCH]"
        description:
        type: youtube
        video_id: "7sluwA4RSoU"
        duration: 782
      - id: "FdH51Ujp-GU"
        title: "UML Tutorial #9 - Aktivit채tsdiagramme"
        description:
        type: youtube
        video_id: "FdH51Ujp-GU"
        duration: 761
      - id: "XClT7gR6hz0"
        title: "UML Tutorial #10 - Aktivit채tsdiagramme #2 - Swim Lanes und Nebenl채ufigkeit"
        description:
        type: youtube
        video_id: "XClT7gR6hz0"
        duration: 472
      - id: "L_auS6pd_l0"
        title: "UML Tutorial #11 - Sequenzdiagramme"
        description:
        type: youtube
        video_id: "L_auS6pd_l0"
        duration: 808
      - id: "dYfr5Opkw38"
        title: "UML Tutorial #12 - Use Case Diagramme"
        description:
        type: youtube
        video_id: "dYfr5Opkw38"
        duration: 649
      - id: "f2A-YfXjl_w"
        title: "Softwareengineering Tutorial #8 - Die Architektur"
        description:
        type: youtube
        video_id: "f2A-YfXjl_w"
        duration: 281
      - id: "oP7bKkTQCYM"
        title: "Softwareengineering Tutorial #9 - Separation of Concerns [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "oP7bKkTQCYM"
        duration: 293
      - id: "V70soZ4obBE"
        title: "Softwareengineering Tutorial #10 - Single Responsibility und Information Hiding"
        description:
        type: youtube
        video_id: "V70soZ4obBE"
        duration: 283
      - id: "a8mTNpp9osg"
        title: "Softwareengineering Tutorial #12 - Least Knowledge, YAGNI und DRY"
        description:
        type: youtube
        video_id: "a8mTNpp9osg"
        duration: 243
      - id: "2g_TRpBfROo"
        title: "Softwareengineering Tutorial #13 - Die 3-Schichtenarchitektur"
        description:
        type: youtube
        video_id: "2g_TRpBfROo"
        duration: 452
      - id: "0vkZGWX73yc"
        title: "Softwareengineering Tutorial #14 - Die 4-Schichtenarchitektur"
        description:
        type: youtube
        video_id: "0vkZGWX73yc"
        duration: 482
      - id: "r5CwZw6Vutc"
        title: "Softwareengineering Tutorial #15 - Die 6-Schichtenarchitektur"
        description:
        type: youtube
        video_id: "r5CwZw6Vutc"
        duration: 279
      - id: "9OtDAgRnGYQ"
        title: "Softwareengineering Tutorial #16 - Die Client-Server Architektur"
        description:
        type: youtube
        video_id: "9OtDAgRnGYQ"
        duration: 285
      - id: "_7FSgpV8FKI"
        title: "Softwareengineering Tutorial #17 - SOA und REST"
        description:
        type: youtube
        video_id: "_7FSgpV8FKI"
        duration: 331
      - id: "gi8jcIIpVIw"
        title: "Softwareengineering Tutorial #18 - Peer-2-Peer Architekturen"
        description:
        type: youtube
        video_id: "gi8jcIIpVIw"
        duration: 336
      - id: "qzNdyvzKtMg"
        title: "Softwareengineering Tutorial #19 - Pipelines"
        description:
        type: youtube
        video_id: "qzNdyvzKtMg"
        duration: 315
      - id: "yAVBMEmx05k"
        title: "Softwareengineering Tutorial #20 - Event-Driven Architecture"
        description:
        type: youtube
        video_id: "yAVBMEmx05k"
        duration: 179
      - id: "c_o_uJ-itz0"
        title: "Softwareengineering Tutorial #21 - Frameworks und Plugins"
        description:
        type: youtube
        video_id: "c_o_uJ-itz0"
        duration: 200
      - id: "xK-nj3J1zXA"
        title: "Softwareengineering Tutorial #22 - Model View Controller MVC"
        description:
        type: youtube
        video_id: "xK-nj3J1zXA"
        duration: 320
      - id: "zVFtyuLFiXg"
        title: "Softwareengineering Tutorial #23 - Entwurf und Muster"
        description:
        type: youtube
        video_id: "zVFtyuLFiXg"
        duration: 328
      - id: "bRHi1JOVGpI"
        title: "Softwareengineering Tutorial #24 - Die Factory Method"
        description:
        type: youtube
        video_id: "bRHi1JOVGpI"
        duration: 258
      - id: "J5_nYHaJEsc"
        title: "Softwareengineering Tutorial #25 - Das Prototype Pattern"
        description:
        type: youtube
        video_id: "J5_nYHaJEsc"
        duration: 213
      - id: "2JCIsj5hVBc"
        title: "Softwareengineering Tutorial #26 - Das Abstract Factory Pattern"
        description:
        type: youtube
        video_id: "2JCIsj5hVBc"
        duration: 306
      - id: "dcdf3E9XO_Y"
        title: "Softwareengineering Tutorial #27 - Das Builder Pattern"
        description:
        type: youtube
        video_id: "dcdf3E9XO_Y"
        duration: 239
      - id: "GUcWjYHmYhY"
        title: "Softwareengineering Tutorial #28 - Dependency Injection [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "GUcWjYHmYhY"
        duration: 351
      - id: "gVaZvrLn48I"
        title: "Softwareengineering Tutorial #29 - Object Pools [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "gVaZvrLn48I"
        duration: 236
      - id: "tBqj1ubwKts"
        title: "Softwareengineering Tutorial #30 - Das Singleton"
        description:
        type: youtube
        video_id: "tBqj1ubwKts"
        duration: 208
      - id: "VKbbVmBpfpQ"
        title: "Softwareengineering Tutorial #31 - Das Adapterpattern"
        description:
        type: youtube
        video_id: "VKbbVmBpfpQ"
        duration: 196
      - id: "q_2ShvmotFc"
        title: "Softwareengineering Tutorial #32 - Der Decorator"
        description:
        type: youtube
        video_id: "q_2ShvmotFc"
        duration: 328
      - id: "TcEMjUmhRjI"
        title: "Softwareengineering Tutorial #33 - Die Fassade"
        description:
        type: youtube
        video_id: "TcEMjUmhRjI"
        duration: 197
      - id: "mo8PRf0BPLE"
        title: "Softwareengineering Tutorial #34 - Die Br체cke/ Das Bridge Pattern"
        description:
        type: youtube
        video_id: "mo8PRf0BPLE"
        duration: 346
      - id: "N6nlWISC5is"
        title: "Softwareengineering Tutorial #35 - Das Flyweight / Fliegengewicht Pattern"
        description:
        type: youtube
        video_id: "N6nlWISC5is"
        duration: 379
      - id: "Gpp4VK2K0tg"
        title: "Softwareengineering Tutorial #36 - Das Proxy Pattern"
        description:
        type: youtube
        video_id: "Gpp4VK2K0tg"
        duration: 311
      - id: "TndId6Y3TGk"
        title: "Softwareengineering Tutorial #37 - Das Observer Pattern aka Publish Subscribe"
        description:
        type: youtube
        video_id: "TndId6Y3TGk"
        duration: 340
      - id: "AC_sgvn48S0"
        title: "Softwareengineering Tutorial #38 - Das Visitor Pattern"
        description:
        type: youtube
        video_id: "AC_sgvn48S0"
        duration: 400
      - id: "q_GSakzwr1A"
        title: "Softwareengineering Tutorial #39 - Das Mediator Pattern"
        description:
        type: youtube
        video_id: "q_GSakzwr1A"
        duration: 201
      - id: "sgyg1fINd_c"
        title: "Softwareengineering Tutorial #40 - Das Strategy Pattern"
        description:
        type: youtube
        video_id: "sgyg1fINd_c"
        duration: 250
      - id: "xaQfItxeFs4"
        title: "Softwareengineering Tutorial #41 - Chain of Responsibility  [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "xaQfItxeFs4"
        duration: 259
      - id: "XXFqKN-Uemc"
        title: "Softwareengineering Tutorial #42 - Das Command Pattern"
        description:
        type: youtube
        video_id: "XXFqKN-Uemc"
        duration: 145
      - id: "Oh-AXdBgos8"
        title: "Softwareengineering Tutorial #43 - Das Memento Pattern"
        description:
        type: youtube
        video_id: "Oh-AXdBgos8"
        duration: 159
      - id: "hZ9wPD32Y4w"
        title: "Softwareengineering Tutorial #44 - Das Template Pattern"
        description:
        type: youtube
        video_id: "hZ9wPD32Y4w"
        duration: 220
      - id: "XdJuzSJhiag"
        title: "Softwareengineering Tutorial #45 - Das Null Object"
        description:
        type: youtube
        video_id: "XdJuzSJhiag"
        duration: 164
      - id: "O5TVlmJGCjQ"
        title: "Softwareengineering Tutorial #46 - Iteratoren"
        description:
        type: youtube
        video_id: "O5TVlmJGCjQ"
        duration: 258
      - id: "DhHgkF-1wF8"
        title: "Softwareengineering Tutorial #47 - Interpreter [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "DhHgkF-1wF8"
        duration: 286
      - id: "fNNWjjMqLyc"
        title: "Softwareengineering Tutorial #48 - Die GRASP - Patterns"
        description:
        type: youtube
        video_id: "fNNWjjMqLyc"
        duration: 611
      - id: "lc9LdxPKwxo"
        title: "Softwareengineering Tutorial #49 - Das Transaction Script"
        description:
        type: youtube
        video_id: "lc9LdxPKwxo"
        duration: 314
      - id: "W-l5jh0LXW4"
        title: "Softwareengineering Tutorial #50 - Das Table Module"
        description:
        type: youtube
        video_id: "W-l5jh0LXW4"
        duration: 228
      - id: "HaYhtv5BaeU"
        title: "Softwareengineering Tutorial #51 - Das Domain Module"
        description:
        type: youtube
        video_id: "HaYhtv5BaeU"
        duration: 203
      - id: "arf_2v02Fk0"
        title: "Softwareengineering Tutorial #52 - Das Record Set"
        description:
        type: youtube
        video_id: "arf_2v02Fk0"
        duration: 296
      - id: "5bf-QpLMon0"
        title: "Softwareengineering Tutorial #53 - Table Data Gateway [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "5bf-QpLMon0"
        duration: 192
      - id: "geVT4x-OMYI"
        title: "Softwareengineering Tutorial #54 - Active Records [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "geVT4x-OMYI"
        duration: 330
      - id: "DaL3ygRX-Xo"
        title: "Softwareengineering Tutorial #55 - Row Data Gateway [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "DaL3ygRX-Xo"
        duration: 327
      - id: "7k7Ygm4ARV8"
        title: "Softwareengineering Tutorial #56 - Single Table Inheritance [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "7k7Ygm4ARV8"
        duration: 297
      - id: "LDEf9r9oixs"
        title: "Softwareengineering Tutorial #57 - Class Table Inheritance [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "LDEf9r9oixs"
        duration: 342
      - id: "cbR8GGwi2-Y"
        title: "Softwareengineering Tutorial #58 - Concrete Table Inheritance [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "cbR8GGwi2-Y"
        duration: 415
      - id: "ODEVZQJbEl0"
        title: "Softwareengineering Tutorial #59 - Die Implementierungsphase: UML in Code umwandeln"
        description:
        type: youtube
        video_id: "ODEVZQJbEl0"
        duration: 441
      - id: "d4gZ89r1_YU"
        title: "Softwareengineering Tutorial #60 - Testen"
        description:
        type: youtube
        video_id: "d4gZ89r1_YU"
        duration: 646
      - id: "TwQ31FmPBMA"
        title: "Softwareengineering Tutorial #61 - Test-Abdeckungen"
        description:
        type: youtube
        video_id: "TwQ31FmPBMA"
        duration: 323
      - id: "e9VHgl95qsc"
        title: "Softwareengineering Tutorial #62 - Kontrollflussgraphen"
        description:
        type: youtube
        video_id: "e9VHgl95qsc"
        duration: 324
      - id: "kg3tpBy4YlQ"
        title: "Microservice Architekturen | Softwareengineering"
        description:
        type: youtube
        video_id: "kg3tpBy4YlQ"
        duration: 549
      - id: "4u4x4Zg5Zpg"
        title: "Aufgaben besser verwalten: Top KANBAN-Boards im Vergleich"
        description:
        type: youtube
        video_id: "4u4x4Zg5Zpg"
        duration: 2068
