# https://www.youtube.com/playlist?list=PLNmsVeXQZj7pkk8-Yxa7mjAqi_E9DE_Z9
title: "Spark und PySpark"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 3000
learning_goals: []
requirements: []
last_update: 1665508416
sections:
  - id: section
    title: "Spark und PySpark für die Supporter"
    description:
    lectures:
      - id: "GbQKhMmfsKE"
        title: "PySpark Tutorial 1   Einleitung und Motivation"
        description:
        type: youtube
        video_id: "GbQKhMmfsKE"
        duration: 844
      - id: "JVuaK8ivKiM"
        title: "PySpark Tutorial 2   Installation"
        description:
        type: youtube
        video_id: "JVuaK8ivKiM"
        duration: 379
      - id: "oKrS5sd-V3E"
        title: "PySpark Tutorial 3   Beispieldaten"
        description:
        type: youtube
        video_id: "oKrS5sd-V3E"
        duration: 619
      - id: "nOxrBzUUEcw"
        title: "PySpark Tutorial 4   DataFrame Grundlagen"
        description:
        type: youtube
        video_id: "nOxrBzUUEcw"
        duration: 418
      - id: "eXtO-CsAQMY"
        title: "PySpark Tutorial 5   eigene Schemas"
        description:
        type: youtube
        video_id: "eXtO-CsAQMY"
        duration: 428
      - id: "81t6mcAl9OQ"
        title: "PySpark Tutorial 6   Mit Dataframes arbeiten"
        description:
        type: youtube
        video_id: "81t6mcAl9OQ"
        duration: 785
      - id: "iBvOxJeww8k"
        title: "PySpark Tutorial 7   SQL"
        description:
        type: youtube
        video_id: "iBvOxJeww8k"
        duration: 272
      - id: "3_WVsntFqI0"
        title: "PySpark Tutorial 8   Daten selektieren"
        description:
        type: youtube
        video_id: "3_WVsntFqI0"
        duration: 634
      - id: "8aj0o74ibCQ"
        title: "PySpark Tutorial 9   Groupby"
        description:
        type: youtube
        video_id: "8aj0o74ibCQ"
        duration: 910
      - id: "IER3vADVs74"
        title: "PySpark Tutorial 10   Missing Data"
        description:
        type: youtube
        video_id: "IER3vADVs74"
        duration: 672
      - id: "4sKsKFUJAcc"
        title: "PySpark Tutorial 11   Datum"
        description:
        type: youtube
        video_id: "4sKsKFUJAcc"
        duration: 516
      - id: "4DPVrmE9N1I"
        title: "PySpark Tutorial 12   Lineare Regression"
        description:
        type: youtube
        video_id: "4DPVrmE9N1I"
        duration: 1259
      - id: "0tpCiSxGcOM"
        title: "PySpark Tutorial 13   Kaufverhalten analysieren mit K Means"
        description:
        type: youtube
        video_id: "0tpCiSxGcOM"
        duration: 819
      - id: "Wnmq1GFhHXg"
        title: "PySpark Tutorial 14   Spark im Cluster nutzen"
        description:
        type: youtube
        video_id: "Wnmq1GFhHXg"
        duration: 515
      - id: "gziO9FV3yqI"
        title: "PySpark Tutorial 15   Praxisprojekt   Ähnliche Lieder auf Spotify"
        description:
        type: youtube
        video_id: "gziO9FV3yqI"
        duration: 1712
