# https://www.youtube.com/playlist?list=PLNmsVeXQZj7pwHqtQSBXGBUNkyGGOJQXf
title: "TypeScript Tutorial Deutsch"
description:
category:
language: de
image:
author: "The Morpheus Tutorials"
price: 0
learning_goals: []
requirements: []
last_update: 1665508373
sections:
  - id: section
    title: "TypeScript Tutorial Deutsch"
    description:
    lectures:
      - id: "uo4PWU-R96k"
        title: "TypeScript Tutorial Deutsch #1 - Die Rettung für JavaScript"
        description:
        type: youtube
        video_id: "uo4PWU-R96k"
        duration: 799
      - id: "_4znAuh0peo"
        title: "TypeScript Tutorial Deutsch #2 - Die IDE"
        description:
        type: youtube
        video_id: "_4znAuh0peo"
        duration: 332
      - id: "H4GV9IbjuuU"
        title: "TypeScript Tutorial Deutsch #3 - Typen"
        description:
        type: youtube
        video_id: "H4GV9IbjuuU"
        duration: 815
      - id: "GIPILAlhs78"
        title: "TypeScript Tutorial #4 - Unions [DEUTSCH/GERMAN]"
        description:
        type: youtube
        video_id: "GIPILAlhs78"
        duration: 233
      - id: "TitI78lrqPs"
        title: "TypeScript Tutorial #5 - Klassen für JavaScript"
        description:
        type: youtube
        video_id: "TitI78lrqPs"
        duration: 481
      - id: "mti14uqp3Ro"
        title: "TypeScript Tutorial #6 - Methoden und Konstruktoren"
        description:
        type: youtube
        video_id: "mti14uqp3Ro"
        duration: 643
      - id: "ACLqaZiFUX0"
        title: "TypeScript Tutorial #7 - Vererbung"
        description:
        type: youtube
        video_id: "ACLqaZiFUX0"
        duration: 547
      - id: "qRZYRXbvqQs"
        title: "TypeScript Tutorial #8 - Überschreiben von Methoden"
        description:
        type: youtube
        video_id: "qRZYRXbvqQs"
        duration: 601
      - id: "ex65d0lVe_s"
        title: "TypeScript Tutorial #9 - Interfaces"
        description:
        type: youtube
        video_id: "ex65d0lVe_s"
        duration: 735
      - id: "FsDZBmKdbu0"
        title: "TypeScript Tutorial #10 - static"
        description:
        type: youtube
        video_id: "FsDZBmKdbu0"
        duration: 253
      - id: "LFhROzaypAA"
        title: "TypeScript Tutorial #11 - Zugriffsmodifikatoren"
        description:
        type: youtube
        video_id: "LFhROzaypAA"
        duration: 580
      - id: "65FKflmpxfA"
        title: "TypeScript Tutorial #12 - Enums"
        description:
        type: youtube
        video_id: "65FKflmpxfA"
        duration: 245
      - id: "crYmfViwgGI"
        title: "TypeScript Tutorial #13 - Generics"
        description:
        type: youtube
        video_id: "crYmfViwgGI"
        duration: 524
      - id: "BZEfP2pBE7I"
        title: "TypeScript Tutorial #14 - Generische Klassen und Constraints"
        description:
        type: youtube
        video_id: "BZEfP2pBE7I"
        duration: 551
      - id: "WOo8SQyBkxQ"
        title: "TypeScript Tutorial #15 - Mehrere Generics"
        description:
        type: youtube
        video_id: "WOo8SQyBkxQ"
        duration: 174
      - id: "nOfG4RvoUkI"
        title: "TypeScript Tutorial #16 - Symbols"
        description:
        type: youtube
        video_id: "nOfG4RvoUkI"
        duration: 442
      - id: "IiZaeAlTMgQ"
        title: "TypeScript Tutorial #17 - For-of-Schleifen"
        description:
        type: youtube
        video_id: "IiZaeAlTMgQ"
        duration: 167
      - id: "JwXejWa_4yo"
        title: "TypeScript Tutorial #18 - Module"
        description:
        type: youtube
        video_id: "JwXejWa_4yo"
        duration: 421
      - id: "P_v-i7Az-O0"
        title: "TypeScript Tutorial #19 - Mehr zu Modulen"
        description:
        type: youtube
        video_id: "P_v-i7Az-O0"
        duration: 419
      - id: "TjNViF9M22k"
        title: "TypeScript Tutorial #20 - Default Exports"
        description:
        type: youtube
        video_id: "TjNViF9M22k"
        duration: 269
