name: Anwendungs-Developer
dependencies:
  - grundlagen_der_programmierung_und_datenhaltung
skills:
  python_fuer_fortgeschrittene:
    name: Python f端r Fortgeschrittene
    dependencies: []
    courses:
      - python_lets_code
      - python_pillow
      - python_pyqt
      - signalverarbeitung
  java_fuer_fortgeschrittene:
    name: Java f端r Fortgeschrittene
    dependencies: []
    courses:
      - java_algorithmen
      - java_fortgeschrittene_techniken
      - java_ray_tracing
      - java_swing
  kotlin_fuer_fortgeschrittene:
    name: Kotlin f端r Fortgeschrittene
    dependencies: []
    courses: 
      - kotlin_fortgeschrittene_techniken
  c_plus_plus:
    name: C++
    dependencies: []
    courses:
      - c
      - cpp
  c_sharp_fuer_fortgeschrittene:
    name: C# f端r Fortgeschrittene
    dependencies: []
    courses: []
