name: Anwendungs-Developer
dependencies:
  - grundlagen_der_programmierung_und_datenhaltung
skills:
  python_fuer_fortgeschrittene:
    name: Python f端r Fortgeschrittene
    dependencies: []
    courses: []
  java_fuer_fortgeschrittene:
    name: Java f端r Fortgeschrittene
    dependencies: []
    courses: []
  kotlin_fuer_fortgeschrittene:
    name: Kotlin f端r Fortgeschrittene
    dependencies: []
    courses: []
  c_plus_plus:
    name: C++
    dependencies: []
    courses: []
  c_sharp_fuer_fortgeschrittene:
    name: C# f端r Fortgeschrittene
    dependencies: []
    courses: []
