name: Cloud Architect
dependencies:
  - systemadministrator
skills:
  grundlagen_der_cloud_administration:
    name: Grundlagen der Cloud-Administration
    dependencies: []
    courses:
      - cloud
