name: Data Scientist
dependencies:
  - algorithmiker
  - datenbank_experte
skills:
  algorithmen_zur_datenanalyse:
    name: Algorithmen zur Datenanalyse
    dependencies: []
    courses:
      - data_mining
  datenanalyse_mit_python:
    name: Datenanalyse mit Python
    dependencies:
      - algorithmen_zur_datenanalyse
    courses:
      - python_data_science
  datenvisualisierung_mit_python:
    name: Datenvisualisierung mit Python
    dependencies:
      - datenanalyse_mit_python
    courses:
      - datenvisualisierung
  python_spark:
    name: Python Spark
    dependencies:
      - datenanalyse_mit_python
    courses:
      - spark_pyspark
