name: Grundlagen von Betriebssystemen
dependencies: 
  - start
skills:
  windows_grundlagen:
    name: Windows Grundlagen
    dependencies: []
    courses:
      - windows10
  powershell_und_fortgeschrittene_windows_administration:
    name: Powershell und fortgeschrittene Windows-Administration
    dependencies: 
      - windows_grundlagen
    courses: []
  linux_grundlagen:
    name: Linux Grundlagen
    dependencies: []
    courses:
      - linux_distributionen
      - linux
  bash_und_fortgeschrittene_linux_administration:
    name: Bash und fortgeschrittene Linux-Administration
    dependencies: 
      - linux_grundlagen
    courses:
      - bash
      - linux_autokey
      - linux_gnupg
