name: Grundlagen der IT-Sicherheit
dependencies:
  - grundlagen_der_netzwerktechnik
  - grundlagen_von_betriebssystemen
skills:
  grundlagen_der_it_sicherheit:
    name: Grundlagen der IT Sicherheit
    dependencies: []
    courses:
      - it_sicherheit_hacken_essentials
  osint:
    name: OSINT
    dependencies:
      - grundlagen_der_it_sicherheit
    courses: []
