name: IT-Forensiker
dependencies:
  - grundlagen_der_it_sicherheit
  - operating_systems_expert
skills:
  assembler:
    name: Assembler
    dependencies: []
    courses: []
  reverse_engineering:
    name: Reverse Engineering
    dependencies:
      - assembler
    courses: []
  wireshark:
    name: Wireshark
    dependencies: []
    courses: []
