name: Machine Learning Expert
dependencies:
  - data_scientist
skills:
  pytorch:
    name: Pytorch
    dependencies: []
    courses:
      - python_pytorch
  tensorflow_mit_python:
    name: Tensorflow mit Python
    dependencies: []
    courses:
      - python_tensorflow
  algorithmen_zum_machine_learning:
    name: Algorithmen zum Machine Learning
    dependencies: []
    courses:
      - machine_learning
