name: Pentester
dependencies:
  - grundlagen_der_it_sicherheit
skills:
  ethik_fuer_hacker:
    name: Ethik für Hacker
    dependencies: []
    courses: []
  grundlagen_des_pentesting:
    name: Grundlagen des Pentesting
    dependencies:
      - ethik_fuer_hacker
    courses: []
  passwortsicherheit:
    name: Passwortsicherheit
    dependencies:
      - grundlagen_des_pentesting
    courses: []
  nmap_expert:
    name: Nmap Expert
    dependencies:
      - grundlagen_des_pentesting
    courses: []
  web_app_pentesting:
    name: Web App Pentesting
    dependencies:
      - grundlagen_des_pentesting
    courses: []
  social_engineering:
    name: Social Engineering
    dependencies:
      - grundlagen_des_pentesting
    courses: []
  binary_exploitation:
    name: Binary Exploitation
    dependencies:
      - grundlagen_des_pentesting
    courses: []
  exploit_researcher:
    name: Exploit Researcher
    dependencies:
      - binary_exploitation
    courses: []
