name: Start
dependencies: []
skills:
  it_grundlagen:
    name: IT-Grundlagen
    dependencies: []
    courses:
      - it-foundations
  medienkompetenz:
    name: Medienkompetenz
    dependencies: []
    courses:
      - medienkompetenz
  it_security_awareness:
    name: IT Security Awareness
    dependencies: []
    courses: []
