name: Start
dependencies: []
skills:
  medienkompetenz:
    name: Medienkompetenz
    dependencies: []
    courses:
      - medienkompetenz
  it_security_awareness:
    name: IT Security Awareness
    dependencies: []
    courses: []
