name: Systemadministrator
dependencies:
  - grundlagen_von_betriebssystemen
  - grundlagen_der_it_sicherheit
skills:
  docker:
    name: Docker
    dependencies: 
      - grundlagen_der_serveradministration
    courses:
      - docker
  nginx:
    name: Nginx
    dependencies: 
      - grundlagen_der_serveradministration
    courses: []
  apache:
    name: Apache
    dependencies: 
      - grundlagen_der_serveradministration
    courses: []
  grundlagen_der_serveradministration:
    name: Grundlagen der Serveradministration
    dependencies: []
    courses:
      - serveradministration
