name: Web Developer
dependencies:
  - grundlagen_der_programmierung_und_datenhaltung
skills:
  html_und_css:
    name: HTML und CSS
    dependencies: []
    courses:
      - css3_fuer_anfaenger
      - html5_fuer_anfaenger
  scss_und_fortgeschrittenes_css:
    name: SCSS und fortgeschrittenes CSS
    dependencies:
      - html_und_css
    courses:
      - sass_scss
  php_grundlagen:
    name: PHP Grundlagen
    dependencies:
      - html_und_css
    courses:
      - php_fuer_anfaenger
  api_konzepte:
    name: API Konzepte
    dependencies:
      - html_und_css
    courses: []
  python_flask:
    name: Python Flask
    dependencies:
      - api_konzepte
    courses:
      - python_flask
  javascript_grundlagen:
    name: Javascript Grundlagen
    dependencies:
      - html_und_css
    courses:
      - javascript
  fortgeschrittenes_javascript:
    name: Fortgeschrittenes Javascript
    dependencies:
      - javascript_grundlagen
    courses:
      - jquery
  serverside_javascript_mit_node_und_express:
    name: Serverside JavaScript mit Node und Express
    dependencies:
      - fortgeschrittenes_javascript
      - api_konzepte
    courses:
      - javascript_express
      - nodejs
  javascript_testing:
    name: Javascript Testing
    dependencies:
      - fortgeschrittenes_javascript
    courses:
      - javascript_jest
      - python_selenium
  typescript:
    name: Typescript
    dependencies:
      - fortgeschrittenes_javascript
    courses:
      - typescript
  react:
    name: React
    dependencies:
      - typescript
    courses: []
  angular:
    name: Angular
    dependencies:
      - typescript
    courses: []
  three_js:
    name: 3D Animationen mit ThreeJS
    dependencies: []
    courses:
      - threejs
