grundlagen_der_programmierung_und_datenhaltung:
  name: Grundlagen der Programmierung und Datenhaltung
  dependencies: []
  courses: [python]
web_developer:
  name: Web Developer
  dependencies: [grundlagen_der_programmierung_und_datenhaltung]
  courses: [javascript]
mobile_app_developer:
  name: Mobile App Developer
  dependencies: [grundlagen_der_programmierung_und_datenhaltung]
anwendungs_developer:
  name: Anwendungs-Developer
  dependencies: [grundlagen_der_programmierung_und_datenhaltung]
game_developer:
  name: Game Developer
  dependencies: [grundlagen_der_programmierung_und_datenhaltung]
software_developer:
  name: Software Developer
  dependencies: [web_developer, mobile_app_developer, anwendungs_developer, game_developer]
computer_grafiker:
  name: Computer Grafiker
  dependencies: [game_developer]
theoretische_programmierkonzepte:
  name: Theoretische Programmierkonzepte
  dependencies: [grundlagen_der_programmierung_und_datenhaltung]
compiler_bauer:
  name: Compiler-Bauer
  dependencies: [theoretische_programmierkonzepte]
datenbank_experte:
  name: Datenbank-Experte
  dependencies: [grundlagen_der_programmierung_und_datenhaltung]
mathematik_fuer_informatiker:
  name: Mathematik für Informatiker
  dependencies: []
algorithmiker:
  name: Algorithmiker
  dependencies: [grundlagen_der_programmierung_und_datenhaltung, mathematik_fuer_informatiker]
computer_scientist:
  name: Computer Scientist
  dependencies: [algorithmiker]
data_scientist:
  name: Data Scientist
  dependencies: [algorithmiker, datenbank_experte]
machine_learning_expert:
  name: Machine Learning Expert
  dependencies: [data_scientist]
soft_skills_fuer_informatiker:
  name: Soft Skills für Informatiker
  dependencies: []
it_paedagoge_und_dozent:
  name: IT-Pädagoge und Dozent
  dependencies: [soft_skills_fuer_informatiker]
grundlagen_der_netzwerktechnik:
  name: Grundlagen der Netzwerktechnik
  dependencies: []
rechnernetze:
  name: Rechnernetze
  dependencies: [grundlagen_der_netzwerktechnik]
grundlagen_von_betriebssystemen:
  name: Grundlagen von Betriebssystemen
  dependencies: []
grundlagen_der_it_sicherheit:
  name: Grundlagen der IT-Sicherheit
  dependencies: [grundlagen_der_netzwerktechnik, grundlagen_von_betriebssystemen]
operating_systems_expert:
  name: Operating Systems Expert
  dependencies: [grundlagen_von_betriebssystemen]
hardware_naher_system_engineer:
  name: Hardware-naher System-Engineer
  dependencies: [operating_systems_expert]
robotik_experte:
  name: Robotik-Experte
  dependencies: [hardware_naher_system_engineer]
it_forensiker:
  name: IT-Forensiker
  dependencies: [grundlagen_der_it_sicherheit, operating_systems_expert]
blockchain_expert:
  name: Blockchain Expert
  dependencies: [grundlagen_der_it_sicherheit]
pentester:
  name: Pentester
  dependencies: [grundlagen_der_it_sicherheit]
blue_team_security_consultant:
  name: Blue Team Security Consultant
  dependencies: [grundlagen_der_it_sicherheit]
systemadministrator:
  name: Systemadministrator
  dependencies: [grundlagen_von_betriebssystemen, grundlagen_der_it_sicherheit]
cloud_architect:
  name: Cloud Architect
  dependencies: [systemadministrator]
devops_engineer:
  name: DevOps Engineer
  dependencies: [cloud_architect]
